### ISSUE TITLE
CPython 3.6+ is switching to a 16-bit wordcode format

### ISSUE THREAD

**Issue by ncoghlan** [pybee/voc#132]
This is an early heads up that CPython will be switching to a 16-bit wordcode format as of 3.6a2: http://bugs.python.org/issue26647

The change itself is in https://hg.python.org/cpython/rev/3a57eafd8401

In theory this should be a transparent change for any project that interacts with compiled code solely through the `dis` module, but since VoC transpiles CPython bytecode I figured you may want to take a closer look at the implications.

**Comment by freakboy3742** [comment]
Thanks for the heads up @ncoghlan. I noticed this go past on python-dev, and assumed it was going to have a pretty big effect, although I hadn't dug into the details yet. Was going to ask around in Portland in a couple of days time.

Are the changes to bytecode format documented, or does this fall into the same "it's documented that it's undocumented, to discourage people from tinkering" hole that the `BUILD_MAP` change came under?

**Comment by freakboy3742** [comment]
Worth noting that this will affect Batavia, as well.

**Comment by freakboy3742** [comment]
There is also a problem with CPython 3.5: the `BUILD_MAP` code changed the order the operands are processed.
