### ISSUE TITLE
Add documentation

### ISSUE THREAD

**Issue by freakboy3742** [pybee/voc#16]
'nuff said. :-)

Anything would be better than just the README.

**Comment by freakboy3742** [comment]
Fantastic! The `/docs` directory already has a basic structure set up; it just needs content. 

The best starting point I can think of at this point is a topic guide describing the interaction between Java classes and Python - how do you implement a Java interface, subclass a Java class, and so on. 

[This code](https://gist.github.com/freakboy3742/3c6b74e8506d47d9bd97) is an example of an Android app written in Python; if you can document and explain the *why* of how it works, especially the inheritance and typing arrangements, that would be a great start.

**Comment by gopar** [comment]
Where would the doc file for the code sample go? Would it just be under the `docs` direcotry? Under what file name would you like to be under? Thanks! \o/

**Comment by freakboy3742** [comment]
@gopar Depends what sort of guide you intend to write. There are a couple of high level sections already set up in the docs:

* **intro** - Documentation for the first interaction with the project - general introductions, explanations and guides to getting an environment working
* **tutorials** - Step by step guides, intended as the first mini-project(s) that the user will run
* **howto** - Step by step guides for how to perform a specific task
* **reference** - Low level, detailed discussion of specific APIs
* **topics** - High level discussions of broad concepts
* **internals** - Detailed descriptions of how internal mechanisms of VOC work. Not especially useful for users; aimed primarily at people wanting to contribute to or modify VOC.

Hopefully that will give you enough guidance to place your contribution. As for specifics like file names - there's no specific guide; anything that makes sense will be fine.

**Comment by eliasdorneles** [comment]
Should this issue be closed now? :)

**Comment by freakboy3742** [comment]
On the basis that there isn't anything specifically actionable, I'm going to say yes.
