### ISSUE TITLE
Adding a linter to travis

### ISSUE THREAD

**Issue by soummyaah** [pybee/voc#186]
A linter needs to be added to travis, one that if possible, reports non-compliance the same way that a test failure reports - "tests passed", but "Python lint failed on file:<>"

**Comment by freakboy3742** [comment]
For context: This came out of a conversation with @soummyaah on a ticket. Ideally the result wouldn't come up *as* a test failure, but as a separate pre-commit report in GitHub.

**Comment by jambonrose** [comment]
Hi Russ,
I'm planning to take a crack at this (if someone is already working on this, please stop me!). I plan to:

- add [flake8](https://pypi.python.org/pypi/flake8) to `requirements/test.txt`
- fix any linting problems (the hard part)
- add a command to `.travis.yml` which runs flake8, and which exits with an error in the event the linter fails

I would also like to add [isort](https://pypi.python.org/pypi/isort).

NB: My understanding of Travis means that this will prevent any tests from running. If we want to run linting and tests, I believe we will need another service such as [code climate](https://codeclimate.com/) or [codacy](https://www.codacy.com/).

**Comment by jambonrose** [comment]
Scratch the post above.

After a conversation between @freakboy3742 and @ldanilov the answer appears to be to use [pybee/beefore](https://github.com/pybee/beefore). Details forthcoming.

**Comment by freakboy3742** [comment]
As @jambonrose indicated, I've been working on pybee/beefore to address this. Beefore needs a few more checks, though:
 * a java linter
 * isort
 * a spell checker for docs
 * a check that docs compile without error

There is also the task of working through all the *existing* code to get it to a lint-less state.

**Comment by cflee** [comment]
Closing this issue as flake8 and checkstyle have since been added to the Travis build.
