### ISSUE TITLE
Impossible to install via pip - no links on PyPI page

### ISSUE THREAD

**Issue by lorenzo-pasa** [pybee/voc#2]
When trying to install Voc as suggested in the documentation:
```
pip install voc
```
an error is raised:
```
Collecting voc
  Could not find a version that satisfies the requirement voc (from versions: )
  No matching distribution found for voc
```
The version of pip is not really the problem (it doesn't work with pip 6.1.1 nor with pip 7.1.2).
Trying to install it with the verbose option leads to the probable root cause:
```
(voc)p@pc:~/voc$ pip install -v voc
Collecting voc
  Getting page https://pypi.python.org/simple/voc/
  Starting new HTTPS connection (1): pypi.python.org
  "GET /simple/voc/ HTTP/1.1" 200 111
  1 location(s) to search for versions of voc:
  * https://pypi.python.org/simple/voc/
  Getting page https://pypi.python.org/simple/voc/
  Analyzing links from page https://pypi.python.org/simple/voc/
  Could not find a version that satisfies the requirement voc (from versions: )
Cleaning up...
No matching distribution found for voc
Exception information:
Traceback (most recent call last):
  File "/home/p/.virtualenvs/voc/local/lib/python2.7/site-packages/pip/basecommand.py", line 211, in main
    status = self.run(options, args)
  File "/home/p/.virtualenvs/voc/local/lib/python2.7/site-packages/pip/commands/install.py", line 294, in run
    requirement_set.prepare_files(finder)
  File "/home/p/.virtualenvs/voc/local/lib/python2.7/site-packages/pip/req/req_set.py", line 334, in prepare_files
    functools.partial(self._prepare_file, finder))
  File "/home/p/.virtualenvs/voc/local/lib/python2.7/site-packages/pip/req/req_set.py", line 321, in _walk_req_to_install
    more_reqs = handler(req_to_install)
  File "/home/p/.virtualenvs/voc/local/lib/python2.7/site-packages/pip/req/req_set.py", line 461, in _prepare_file
    req_to_install.populate_link(finder, self.upgrade)
  File "/home/p/.virtualenvs/voc/local/lib/python2.7/site-packages/pip/req/req_install.py", line 250, in populate_link
    self.link = finder.find_requirement(self, upgrade)
  File "/home/p/.virtualenvs/voc/local/lib/python2.7/site-packages/pip/index.py", line 571, in find_requirement
    'No matching distribution found for %s' % req
DistributionNotFound: No matching distribution found for voc
```
The root cause is probably the page https://pypi.python.org/simple/voc/, being it completely blank.

**Comment by Foxboron** [comment]
You can do `pip install git+https://github.com/pybee/voc.git`

**Comment by lorenzo-pasa** [comment]
Yes, it works =)
At least, finding the problem gave me the opportunity to create a pull request to update the README file.
Of course that pull request doesn't really close this issue, imho. 
The links on PyPI page are still missing.

**Comment by freakboy3742** [comment]
Thanks for the report - I've fixed it by pushing a v0.0.1 initial release to PyPI.

**Comment by Alex-Bogdanov** [comment]
I have encountered this problem trying to install any other package from PyPi (requests, pip, jsonschema).
    python34 -m pip install -U pip==7.1.2
    Collecting pip==7.1.2
    Could not find a version that satisfies the requirement pip==7.1.2 (from versions: )
    No matching distribution found for pip==7.1.2

Anybody knows what a hell is that? It reproduced for Python 3.4.1 and now for 3.4.3. This forced me to use easy_install instead of pip((

**Comment by freakboy3742** [comment]
@Alex-Bogdanov This seems to be more of a problem with your use of pip, rather than voc. I can't see anything obviously wrong with your usage, and the command you've provided works for me. If it's not a transient problem caused by a temporary PyPI outage, I'd suggest taking this to the PyPA people and getting their feedback.
