### ISSUE TITLE
Python exceptions cant be raised. 

### ISSUE THREAD

**Issue by nisdop** [pybee/voc#249]
I have a problem with exception raises.

1.Cant raise exception by class name.
```
test.py
---------------------
raise ValueError

```
```
  File "/home/user/Projects/voc/voc/python/ast.py", line 489, in visit_Raise
    exception = 'org/python/exceptions/%s' % node.exc.func.id
AttributeError: 'Name' object has no attribute 'func'

```

2.Cant raise instance of exception without arguments
```
test2.py
---------------------
raise ValueError()

```
```
   File "/home/inekipelov/PosterProjects/voc/voc/java/constants.py", line 391, in __init__
    self.descriptor = method_descriptor(descriptor)
  File "/home/inekipelov/PosterProjects/voc/voc/java/signatures.py", line 179, in method_descriptor
    return MethodDescriptor(parameters=matches[:-1], return_type=matches[-1])
IndexError: list index out of range
```

**Comment by freakboy3742** [comment]
Thanks for your report. The first one doesn't surprise me, but the second one does. 

If you're looking to contribute, this could be relatively easy place to begin. Encoding these two cases as test cases that are known failing tests will be a 5-10 line patch; actually fixing these problems will require a bit more digging, but would give you a good introduction to the internals of VOC.

**Comment by nisdop** [comment]
I'm working on it.
