### ISSUE TITLE
Install issue on Ubuntu 16.04 libpython3.4-testsuite

### ISSUE THREAD

**Issue by wesseljb** [pybee/voc#253]
Hi,
I'm in the process of installing the dev environment for VOC and when I tried to install 3.4 and got the following error

```
Reading package lists... Done
Building dependency tree       
Reading state information... Done
E: Unable to locate package libpython3.4-testsuite
E: Couldn't find any package by glob 'libpython3.4-testsuite'
E: Couldn't find any package by regex 'libpython3.4-testsuite'
```

I had to run the following command to fix it:

```
sudo apt-get install libpython3.5-testsuite
```

**Comment by freakboy3742** [comment]
Confirmed - the instructions were written for Ubuntu 14.04 (or 12.04... I can't remember :-). 16.04 needs the adjustment described.

**Comment by wesseljb** [comment]
I am going to try and make the changes and then do a pull request


On 21 September 2016 at 09:35, Russell Keith-Magee <notifications@github.com

**Comment by wesseljb** [comment]
I logged a pull request, hope that is fine.
