### ISSUE TITLE
Update python version requirement to 3.5+

### ISSUE THREAD

**Issue by manparvesh** [pybee/voc#270]
Please update the python version requirement to 3.5+ instead of 3.4+.
It took me a lot of time to figure this out, since I had Python 3.5.2 installed on my system and still, while installing VOC, I got error message saying:
`VOC requires Python 3.4+`  
This was resolved once I changed this in the `setup.py` file.

**Comment by freakboy3742** [comment]
As noted on #271, it's not quite as simple as just updating a version reference; there a fundamental differences between Python 3.4, 3.5 and 3.6.

If you're particularly invested in Python 3.5, merging the work from the master branch into the 3.5 branch and making whatever adjustments are required would be deeply appreciated.

I'll keep this ticket open as a flag for Python 3.5+ support.

**Comment by manparvesh** [comment]
I understand. I would go through this again properly in that case.

**Comment by brechtm** [comment]
This breaks installation of briefcase, even though my use case doesn't require VOC (creating a macOS .app)!

**Comment by brechtm** [comment]
Installation from wheel is still possible. You might want to perform this check on import of voc instead.

**Comment by freakboy3742** [comment]
@brechtm Thanks for the report - that's clearly an unintended side effect.

**Comment by shaib** [comment]
Since #326 was merged, is this still pertinent?
Note that #326 does not provide full Python 3.5 support, not all the tests pass, but the complete breakage should no longer be there.

**Comment by freakboy3742** [comment]
@shaib *This* issue can be closed; but there's at least two follow up issues - making the 3.5 test suite pass (and adding it to CI); and modifying the import process so that it doesn't break briefcase (although that might be a fix to Briefcase that is required).
