### ISSUE TITLE
Correct documentation

### ISSUE THREAD

**Issue by libertil** [pybee/voc#281]
In the getting started section of the docs should be mentioned that voc won't build on Python3.5+.
The default version apt-get provides on Ubuntu 16.04 is 3.5+, it should be mentioned that a separate 
Python 3.4+ is required. 
Accordingly in the page "Contributing to VOC" 
https://voc.readthedocs.io/en/latest/internals/contributing.html
there shouldn't be a reference to libpython3.5-testsuite.

**Comment by freakboy3742** [comment]
Thanks for the suggestion. I can see how this would be confusing, so a documentation fix is definitely called for.

**Comment by g-akash** [comment]
Hi, I would like to work on this.

**Comment by svatsan** [comment]
Fixed in 0331a80. Please close this ticket
