### ISSUE TITLE
Use Array instead of List in Tuple type

### ISSUE THREAD

**Issue by shaib** [pybee/voc#327]
Current `org.python.types.Tuple` uses a `List<Object>` as its internal implementation; takes a List as its argument constructor and stores a reference to it.

This is sub-optimal, because a Python tuple is immutable. An Array would avoid dragging in all the resize mechanisms.

But further, it is incorrect, because a Python tuple should not change when the value used to construct it changes.

**Comment by shaib** [comment]
My reading of the code is that this will fail, before and after #343:
```python
lst = [1,2,3]
tpl = tuple(lst)
lst.append(4)
assertEqual(tpl, (1,2,3))
```
Haven't tested it yet, could be wrong...

**Comment by cflee** [comment]
It seems to fail because the `tuple()` builtin (and seemingly most of the other datatype builtins) is not implemented yet, but that does seem like a possible issue!

Adding some failing test cases would be very helpful for the future implementer.
