### ISSUE TITLE
Correct the reference for implementantion of __mul__() 

### ISSUE THREAD

**Issue by knaggita** [pybee/voc#337]
In Your-first-VOC-contribution.md, a wrong reference is given for the implementation of the __mul__() function. 

https://github.com/pybee/voc/blob/master/python/common/org/python/types/Str.java#L309

**Comment by freakboy3742** [comment]
Thanks for pointing this out. This is going to be an ongoing problem as the source code keeps changing; ideally we'd be able to link to a method, rather than a specific line number.

**Comment by whydoubt** [comment]
I don't know about Your-first-VOC-contribution.md (is that an older file? a generated file? somewhere I'm not looking?) but https://github.com/pybee/pybee.github.io/blob/lektor/content/contributing/how/first-time/what/voc/contents.lr seems to contain the relevant text.  It appears that it is now referencing a particular commit, to avoid the shifting line problem.

I think this particular issue should be marked closed.

**Comment by cflee** [comment]
The [Your First VOC Contribution](https://pybee.org/contributing/how/first-time/what/voc/) page on pybee.org (which the README now links to, instead of the previous markdown file in this repo) now links to a specific commit, so this is resolved indeed.

Thanks @whydoubt!
