### ISSUE TITLE
Integrate Ouroboros into the build

### ISSUE THREAD

**Issue by freakboy3742** [pybee/voc#348]
[pybee/Ouroboros](https://github.com/pybee/ouroboros) provides a pure Python implementation of the Python standard library. That Python code can be compiled directly into Java classifies and converted into a standard library that can ship as part of the VOC support libraries, supplemented by native implementations as required (see pybee/voc#74).

**Comment by eliasdorneles** [comment]
So, how do you think this integration could work initially?

Right now, ouroboros doesn't compile with VOC yet, do you think we should get VOC complete enough to compile ouroboros before doing this integration?

Or do you think it would be valuable start with something like, adding an extra build step that tries to compile every file in ouroboros, check how many compile without errors and report if that number diminishes?
I know that simply compiling without errors doesn't mean it's generating the correct code, but it may be a cheap way to prevent some kinds of breaking changes.

**Comment by eliasdorneles** [comment]
I've just ran a quick check in my laptop, to see how many files would compile without errors:

    for f in ouroboros/*.py; do voc $f && (echo WORKS >> log.txt) || (echo FAILS >> log.txt); done

It resulted in this:

    $ sort log.txt | uniq -c
    125 FAILS
     45 WORKS

Well, this is a run only for the files in the top level, but it means it's compiling ~26% of the files without errors.
It would be cool to ensure that this percentage doesn't go down.

**Comment by eliasdorneles** [comment]
Full output that can be useful: https://gist.github.com/eliasdorneles/2087a1f8df316d23ac0520533c9c47a5
I'll mine it for interesting bugs later. :)

**Comment by freakboy3742** [comment]
An approach like Batavia uses would be helpful - keep a list of modules that are implemented and tested, and use that list as the manifest of what to compile into the main sources. That effectively white-lists modules that we know work (like the 45 that are currently compiling without problem)

The debug output is definitely interesting, though - lots of good material to mine there.

**Comment by eliasdorneles** [comment]
I've re-run the compilation for Ouroboros using this command and I've added the results [to this gist](https://gist.github.com/eliasdorneles/c64fae2d6aa1dea85602be29508f3c40), together with a simple log analysis command that display the most common error messages, this may help prioritize what to fix.

**Comment by eliasdorneles** [comment]
I think we can close this one already, the tool from #626 is running every time we do `ant java`.
