### ISSUE TITLE
Setting instance attributes is failing to overwrite class attributes

### ISSUE THREAD

**Issue by eliasdorneles** [pybee/voc#362]
For the following program:

```
class MyClass:
    someattr = 1


print(MyClass.someattr)

inst = MyClass()
print(inst.someattr)

inst.someattr = 123
print(inst.someattr)
print(MyClass.someattr)
```

... the expected behavior in Python is:

```
$ python overwrite_class_attrs.py
1
1
123
1
```

What you get with VOC:

```
+ java -cp ../voc/dist/python-java-support.jar:. python.overwrite_class_attrs.__init__
1
1
1
1
```

It seems to be always using the class attribute and disregarding the reassignment.

**Comment by eliasdorneles** [comment]
I should mention that this might also be a bug in the code that reads the attribute.

**Comment by sohit-nayak** [comment]
Hi, this actually looks quite interesting.. Could anyone advice on how to start??

**Comment by tbliu** [comment]
Hi, I would also like to work on this bug and am looking for advice/pointers! Thanks!
