### ISSUE TITLE
Some expressions in list comprehensions causes runtime crash

### ISSUE THREAD

**Issue by eliasdorneles** [pybee/voc#369]
I'm running into an interesting issue with list comprehensions, here's the test case:

```
$ cat testrange.py 

# this works:
print([i+1 for i in range(3)])

# this also works:
print(list(i for i in range(3)))

# this crashes:
print([i for i in range(3)])
```

Running this with Python gives the expected output:

```
$ python testrange.py 
[1, 2, 3]
[0, 1, 2]
[0, 1, 2]
```

Running with VOC (java and javac 1.8, Python 3.4), I get a "tuple index out of range" error:

```
$ java -cp ../voc/dist/python-java-support.jar:. python.testrange.__init__
[1, 2, 3]
[0, 1, 2]
Exception in thread "main" IndexError: tuple index out of range
	at org.python.types.Tuple.__getitem__(Tuple.java:334)
	at org.python.types.Function.populateAttrs(Function.java:41)
	at org.python.types.Function.<init>(Function.java:153)
	at python.testrange.__init__.module$import(testrange.py:9)
	at python.testrange.__init__.main(testrange.py)
```

**Comment by gEt-rIgHt-jR** [comment]
Hi, I would like to solve this issue. I want some help.
From what I have understood, the reason is that the size of [`co_const`](https://github.com/pybee/voc/blob/master/python/common/org/python/types/Function.java#L39) is zero.
Can someone tell me where it is initialized and how can I solve this?

**Comment by deep110** [comment]
@gEt-rIgHt-jR I think _co_const_ is initialized [here](https://github.com/pybee/voc/blob/master/python/common/org/python/types/Function.java#L111).

**Comment by gEt-rIgHt-jR** [comment]
@deep110 I think [this](https://github.com/pybee/voc/blob/master/python/common/org/python/types/Function.java#L130) constructor is used, but I don't know when it is called.
