### ISSUE TITLE
Float addition is not taking complex into account

### ISSUE THREAD

**Issue by deep110** [pybee/voc#373]
In CPython when we intialize x = 1.5+2j, x is taken as a complex type, but voc gives error with 

> TypeError: unsupported operand type(s) for +: 'float' and 'complex'

There need to be some modification done in __add()__ of Float.

**Comment by deep110** [comment]
Nope, it is working as expected, Sorry it was my blunder, I don't have access to delete this, if any1 can please do it. Thanks.

**Comment by glasnt** [comment]
Hi @deep110. GitHub issues can't be deleted, but don't worry, closing the issue is fine.
