### ISSUE TITLE
Undefined for loop (NameError), when iterating over something created by same generator function

### ISSUE THREAD

**Issue by eliasdorneles** [pybee/voc#376]
When I run this code:

```
$ cat testgen.py 
def somegen():
    for it in [1, 2, 3]:
        yield it


for a in somegen():
    for b in somegen():
        print(a, b)
```

Under Python, I get the expected:

```
$ python testgen.py 
1 1
1 2
1 3
2 1
2 2
2 3
3 1
3 2
3 3
```

Running through VOC, I get:

```
+ java -cp ../voc/dist/python-java-support.jar:. python.testgen.__init__
1 1
1 2
1 3
Exception in thread "main" NameError: name '#for-iter-7f0963a710f0' is not defined
	at org.python.types.Module.__getattribute__(Module.java:38)
	at python.testgen.__init__.somegen$generator(testgen.py:2)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.python.types.Generator.__next__(Generator.java:57)
	at python.testgen.__init__.module$import(testgen.py:6)
	at python.testgen.__init__.main(testgen.py)
```

Note how it breaks on second iteration of the for loop -- it seems that it's cleaning up the name before it should.

Another hint to the problem is that using a second generator function with the same code works correctly, namely, the following code gives the correct output:

```
def somegen():
    for it in [1, 2, 3]:
        yield it

def othergen():
    for it in [1, 2, 3]:
        yield it

for a in somegen():
    for b in othergen():
        print(a, b)
```

**Comment by ashwani99** [comment]
Hi, I want to work on this. Can I get some help on how it can be done?

**Comment by eliasdorneles** [comment]
@ashwani99 Sure, I can give you some pointers.

This seems to be a bug in the bytecode generated for the for loop, in [the visit_For method](https://github.com/pybee/voc/blob/master/voc/python/ast.py#L459).
If you look at that code closely, you'll notice that it creates a for loop giving it a name here: https://github.com/pybee/voc/blob/master/voc/python/ast.py#L472

From looking at the error (NameError on a `#for-iter-SOMETHING`), it seems that the [deletion of the for loop name](https://github.com/pybee/voc/blob/master/voc/python/ast.py#L516) may be executing too soon in this specific case (iterating from inside a generator created inside another generator).

Be sure to checkout the [section on the docs about contributing](http://voc.readthedocs.io/en/latest/internals/contributing.html), specially the section about [working with code for Java byteode](http://voc.readthedocs.io/en/latest/internals/contributing.html#working-with-code-for-java-bytecode)

**Comment by eliasdorneles** [comment]
I tested this again with the latest code, and can't reproduce it -- this doesn't seem to be an issue anymore, so I'm closing it.
