### ISSUE TITLE
Ouroboros Compile Issue with VOC

### ISSUE THREAD

**Issue by ashutoshsaboo** [pybee/voc#456]
Hello, 
So I've been trying a lot, since the last 4 days, to get my head into this. After a lot of problems, I thought, that I must first work on resolving the compile issue of a particular file of VOC, that's failing currently, so that things can become easier ahead. On the contrary, this is giving some more problems itself. 

For debugging purposes, I am printing the node value, that's being traversed in the Visitor() class of ast.py.

I tried compiling 3 python scripts with VOC-:
1. example1.py - contains the exact same `ouroboros.collections.py` It's error log can be found at `example1_log_with_node_names.txt` . Please note the order in which the nodes are printed, and the final line number as well (it's mentioned in the last line), where the error appears.

2. example2.py - This is just a sample generator function which compiles perfectly with VOC. It's compile log can be found at `example2_log_with_node_names.txt`.

3. example3.py - Basically contains example2.py's generator method added to the top of `example1.py`. It's compile log can be found at `example3_log_with_node_names.txt`

This is the GitHub GIST link - https://gist.github.com/ashutoshsaboo/52be09c551b8ffaedf35b727378bf2d8 which can be referred to for all these files. 

Certain observations:
1. If we notice the order of nodes that are visited in example2.py, and example3.py, what's the change is that, in example2.py - a BinOp is generated inside the Yield node , whereas in example3.py - a Attribute Node is generated inside the Yield node.

2. From this, we might presume that there could be some problem related to `VOC`'s code base in general itself, but if the compile log of `example3.py` and `example2.py` is compared, we can see that, the method that we wrote in `example2.py` compiles perfectly. So there's some issue related to node generation with respect to the `ast module` for `Classes` in general itself. 

I've been caught up in this problem, and it would be really great, if someone could help on this. 

@eliasdorneles @cflee @freakboy3742 Any help from you would be really great!

**Comment by glasnt** [comment]
Thanks for the report. At this stage, VOC is still very much a work in progress, but at this point, what you're trying to do is definitely not working yet. It's also a very large chunk of work.

Let's break things down a bit. You've been commenting in gitter recently about things "not working", but we're still not entirely sure what you want to achieve. Are you just trying to implement NamedTuples? This is functionality that is one small part of the entire Collection module. Once VOC is fully operational, we'll be able to use the Python implementation of the Collections module, which is defined as part of Ouroboros, and get all the benefits of the Collections module without needing to write anything specific.

However, you're trying to import ALL of collections before VOC is fully complete.

VOC, and the entire BeeWare suite, is a iterative process. Can you reduce the problem to a minimal example (or examples) that don't work? What we need are small, well defined demonstrations of problems - like what was done here: pybee/voc#382

If you encounter issues, it greatly helps the core development team if you explain three things with your bug report: A) What you're trying to achieve, B) the exact error you're getting as a text, and C) what you've tried to do to correct the error.

Thanks!

**Comment by ashutoshsaboo** [comment]
Hi @glasnt . Thanks. 

What I was trying to do with NamedTuple was basically start the native collections module for VOC itself. I didn't knew then the Ouroboros had a native implementation already. That was the problem. 

I understand your point, for a minimal test case. I'll look into it. And the minimal thing here, is mostly that `yield` is not working in the same way with `self - classes` and without them. For the latter case, it works perfectly, on the other hand for the first one it doesn't work fine. (My point number 2 in the Issue's main post). I guess we need to look at the `classes` transpilation for VOC.

Though I'm not sure about this, but after all the debugging, that seems to be the root cause of the problem at-least. And that is what, we could also infer from `example1.py` , `example2.py` as well as `example3.py` . What I wanted to work on was basically work on atleast making VOC compile all the Ouroboros files, for which the methods are already defined. For instance, currently VOC can already handle `yield` instances, and hence it should be able to compile the yield methods within the `collections.py` file as well, i.e, the error shouldn't be at the `yield` statement i mean, which is happening now. For other instances like, `lambda` and others as well, which aren't supported by VOC yet, it's fine if it can't compile the files. 

I hope to work on this more, so that we can move a step ahead towards the resolution for this issue! :smile: Would be great to have your points on this @glasnt @freakboy3742 @cflee @eliasdorneles ! :+1:
