### ISSUE TITLE
GSoC: Complete implementation of the str, float and int types

### ISSUE THREAD

**Issue by McMastS** [pybee/voc#464]
# Task: 
Complete implementation of the str, float and int types
# Success: 
100% completion of every method and operation on type str, int and float before the end date of August 29, 2017
# Design Specifications:
The string portion of this project will contain a total of 18 methods and operations to complete. For this project, I have grouped each of these tasks into three separate difficulty levels: complex, semi-complex, simple. The 90 days of coding will be mostly spent on the complex and semi-complex methods and operations, while the simple ones will be scheduled in between the more difficult methods. Additionally, the documentation must be completed on every method.

The float and int methods are both mostly missing the right operators (__rmul__, __radd__, etc.) which should not be difficult to implement.
The methods that will need special attention (complex or semi-complex) are:
### encode
-Will be a difficult method to implement, and will require prior researching
-A cursory search indicates that java has some str methods which will help (getBytes()), but I still anticipate this method to prove a challenge
**Estimated time:** 4 days coding, plus more thorough research during Community Bonding Period
### casefold
-Requires the understanding and implementation of the casefolding algorithm, along with a greater understanding of the Unicode Standard 
**Estimated time:** 3 days coding, plus research during Community Bonding Period
### format and format_map
-Both these methods must be able to handle multiple arguments, keyworded as well
-Difficulty in implementation may arise from dealing with dictionaries as arguments
-These methods should be similar in implementation, so I have grouped them together. The main difference is the handling of dict types as arguments 
**Estimated time:** 5 days
### maketrans and translate
-The dictionary aspect of the maketrans() method could prove to be difficult to implement, as the table will need to have corresponding values
-translate() could be semi-complex but I have grouped it with maketrans() as they must be compatible, and translate does require Unicode handling which adds to the complexity of the method
**Estimated time:** 4 days
### isidentifier, isprintable, isnumeric
-All these methods use Unicode, but checking to see if equal should be simpler than some of the other complex methods using Unicode
**Estimated time:** 1 day each, plus possible extra .5 day each for unanticipated trouble

_All other methods are simple and should take 1 day or less. Float and int operators are included in the simple category._ 

# Timeline

**May 4-May 30 (Community Bonding Period)**
* Investigate and research Unicode, encoding and how to implement a hashmap to emulate a dictionary   in Java
* Participate in community discussions on Gitter, and other platforms
* Get up to date on all documentation

**May 30-June 2 (Week 1)**
* Implement, test and document str.isidentifier, str.isnumeric, str.isprintable
* Continue communicating with community
* Investigate str.encode and Unicode

**June 5-9 (Week 2)**
* Implement, test and document str.casefold
* Implement, test and document str.splitlines
* Continue researching str.encode and begin investigating hashmaps again

**June 12-16 (Week 3)**
* Implement, test and document str.format and str.format_map
* If time allows, begin completing documentation of undocumented methods 

**June 19-23 (Week 4)**
* If necessary, finish str.format and str.format_map 
* Implement, test and document str.translate
* Investigate str.maketrans (Unicode handling, possible algorithms) if time permits

**June 26-30 (Week 5)**
* Implement, test and document str.replace
* Start implementation of str.maketrans

**Phase 1 Evaluation due June 30**

**July 3-7 (Week 6)**
* Finish implementation of str.maketrans
* If possible, start implementation of str.rpartition
* Investigate implement of float and int methods thoroughly

**July 10-14 (Week 7)**
* Finish str.rpartition
* Implement, test and document str.encode

**July 17-21 (Week 8)**
* Finish str.encode
* Finish documentation of undocumented methods

**July 24-28 (Week 9)**
* Finish all remaining simple methods on the str type
* If needed and if time permits, investigate int and float methods

**Phase 2 Evaluation due July 28**

**July 31-August 4 (Week 10)**
* If necessary, finish the remaining methods on str
* Implement float’s r methods
* Implement as many of int’s r methods as possible

**August 7-11 (Week 11)**
* Implement  float.\_\_dir__ and float.format
* Implement str.\_\_dir__

**August 14-18 (Week 12)**
* Implement float.\_\_pow__ for modulo
* Finish implementation of int’s r methods

**August 21-29 (Final Week)**
* Complete implementation of int, which includes int.\_\_dir__, int.\_\_format__ and int() with a base
* Submit final work and mentor evaluation

I will include my personal information and other info I omitted in the final application for GSoC. Looking forward to any feedback!

Edit: Added suggestions given by @freakboy3742. Any more feedback is appreciated!

**Comment by freakboy3742** [comment]
@McMastS This looks great. You've clearly done a lot of research, and this is quite clear about what you're intending. A couple of comments:

* Unicode handling is definitely complex, but I'm not sure if `encode` will be as difficult as you think; there should be existing code that implements encoding algorithms, probably in the Java standard library. If you've investigated these options and I'm wrong, please correct me (and elaborate the outcome of that research in the proposal!)

* While the enthusiasm is great to hear, I'd rather not see a schedule that *plans* on weekend work. Work-life balance matters; I'd rather see a project schedule slip by a day than see you working over weekends.

* The `r` operators - I would have thought you could pretty much do *all* of those in a day - is there some complexity here that I'm missing? Isn't it just reversing order of invocation on the base operations?

* You may need to adjust these estimates based on patches that have landed recently (e.g., strip has landed recently)

* I'm wary of estimates that include 1-3 weeks of "contingency". Tasks like submission and mentor evaluation are also unhelpful. This is a 12 week program; we're expecting you to have a plan for the whole 12 weeks. *No* software engineering plan survives it's first encounter with reality, so it's not expected that your plan will be 100% accurate down to the last hour. However, you should still have a plan for what you're going to do for a full 12 weeks.

**Comment by McMastS** [comment]
@freakboy3742 Thanks for the feedback! 
* I haven't investigated encode other than some cursory searches which made me think it would be difficult, however I will do some more research and add that to my proposal.
* Thanks for bringing up work-life balance, in my excitement it slipped my mind.
* After looking into the r operators further, you're correct, I had just done a simple search and I misunderstood what is required for each method
* On the contingency, I was wary of proposing a project that was too ambitious, but now that I've looked into it further I think I could fill that time by adding another type to complete. Do you have any suggestions on which my time would be best spent?

Thanks again.

**Comment by freakboy3742** [comment]
@McMastS Preference would be the more common types; given that you're looking at str and float, int would seem like a natural match.

**Comment by freakboy3742** [comment]
Unfortunately, this proposal wasn't accepted.
