### ISSUE TITLE
GSoC Proposal: Implementation of Dict, Set, and FrozenSet

### ISSUE THREAD

**Issue by ad1269** [pybee/voc#468]
# Proposal

I’d like to complete the implementations of the Set datatype, the Dict datatype, and the FrozenSet datatype. There are also some bugs in the frozen set constructors that results in an IndexOutOfBoundsException, so I will fix that. In addition, I’d like to refactor some of the iterators for common iterables such as tuples, strings, and ranges to fit the standard iterator pattern. I have provided a specific list of functions and features I’d need to code below. I’ve tested all of these functions on VOC, and they all need work to match the behavior in Python. Please let me know what if you have any feedback on my proposal! Thanks in advance 😄 !

## Goal

I would count my summer as a success if I complete the implementations of the following functions and features. If I get ahead of schedule, I will work on implementing additional functions for these three classes.

## Features

1. Iteration support for Dictionaries (Already implemented by me.)
2. Iteration support for Sets
3. Iteration support for FrozenSets
4. Refactor iterator for Tuples
5. Refactor iterator for Strings
6. Refactor iterator for Ranges

#### Dict Datatype
1. dict.keys()
2. dict.values()
3. dict.update(Object other)
4. dict.__dir__()
5. dict.__eq__() (Partially implemented, need to complete implementation.)
6. dict.__ge__()
7. dict.__gt__()
8. dict.__le__()
9. dict.__lt__()
10. dict.__format__(Object other)

#### Set Datatype
1. set.isdisjoint(Object other)
2. set.issubset(Object other)
3. set.issuperset(Object other)
4. set.symmetric_difference(Object other)
5. set.symmetric_difference_update(Object other)
6. set.__dir__()
7. set.__eq__() (Partially implemented, need to complete implementation.)
8. set.__ge__() (Partially implemented, need to complete implementation.)
9. set.__gt__() (Partially implemented, need to complete implementation.)
10. set.__le__() (Partially implemented, need to complete implementation.)
11. set.__lt__() (Partially implemented, need to complete implementation.)
12. set.__format__(Object other)
13. set.__sub__()
14. set.__and__()
15. set.__or__()
16. set.__xor__()
17. set.__rsub__()
18. set.__rand__()
19. set.__ror__()
20. set.__rxor__()

#### FrozenSet Datatype
1. frozenset.isdisjoint(Object other)
2. frozenset.issubset(Object other)
3. frozenset.issuperset(Object other)
4. frozenset.symmetric_difference(Object other)
5. frozenset.__dir__()
6. frozenset.__eq__()
7. frozenset.__ge__()
8. frozenset.__gt__()
9. frozenset.__le__()
10. frozenset.__lt__()
11. frozenset.__format__(Object other)
12. frozenset.__sub__()
13. frozenset.__and__()
14. frozenset.__or__()
15. frozenset.__xor__()
16. frozenset.__rsub__()
17. frozenset.__rand__()
18. frozenset.__ror__()
19. frozenset.__rxor__()

## Timeline

I expect to implement and thoroughly test 5 functions per week for the Dict type, and 5 functions every 2 weeks for the Set and FrozenSet types. Since features are so similar between sets and frozen sets, I’ll code them and test them in adjacent weeks. My timeline is as follows.

May 4 - May 30 (Community Bonding Period)
* Explore each of these datatypes implementations in detail
* Write simple exploratory tests to hash and pin down function details
* Interact with the community on Gitter, and ask for help on any preliminary issues I may run into
* Research the __format__ method, and the format specification mini-language.

May 30 - June 2 (Week 1)
* Begin working on the Dict datatype.
* Implement and test: keys, values, update, __dir__, and __eq__

June 5 - 9 (Week 2)
* Continue working on the Dict datatype.
* Implement and test: __ge__, __gt__, __le__, __lt__, and __format__
* __format__ will be more difficult to implement, I’d like to finish the comparison methods within 2 days, and spend 3 days on __format__

June 12 - 16 (Week 3)
* Begin working on the Set datatype.
* Begin implementation and testing: __xor__, __rsub__, __rand__, __ror__, and __rxor__

June 19 - 23 (Week 4)
* Begin working on the FrozenSet datatype.
* Finish implementation and testing: __xor__, __rsub__, __rand__, __ror__, and __rxor__

June 26 - 30 (Week 5)
* Continue working on the Set datatype.
* Begin implementation and testing: __eq__, __sub__, __and__, __or__, and __dir__

July 3 - 7 (Week 6)
* Continue working on the FrozenSet datatype.
* Finish implementation and testing: __eq__, __sub__, __and__, __or__, and __dir__

July 10 - 14 (Week 7)
* Continue working on the Set datatype.
* Begin implementation and testing: isdisjoint, issubset, issuperset, symmetric_difference, symmetric_difference_update

July 17 - 21 (Week 8)
* Continue working on the FrozenSet datatype.
* Finish implementing and testing: isdisjoint, issubset, issuperset, symmetric_difference

July 24 - 28 (Week 9)
* Continue working on the Set datatype.
* Begin implementation and testing: __ge__, __gt__, __le__, __lt__, and __format__

July 31 - August 14 (Week 10)
* Continue working on the FrozenSet datatype.
* Finish implementation and testing: __ge__, __gt__, __le__, __lt__, and __format__
* __format__ will be more difficult to implement, I’d like to finish the comparison methods within 4 days, and spend 6 days on __format__

August 7 - 11 (Week 11)
* Complete iteration support for Set, String, and Tuple

August 14 - 21 (Week 12)
* Complete iteration support for FrozenSet and Range

**Comment by freakboy3742** [comment]
@ad1269 Thanks for submitting this proposal. Some comments:

* The biggest thing that stands out to me is that you don't appear to make any reference to the fact that frozenset and set are almost identical data types. So - lets assume your week 7 estimate for implementing isdisjoint, is subset, is superset, etc is correct: Why is the estimate for week 8 - implementing the same methods for FrozenSet - *exactly the same*? Aren't the implementations going to be *identical*? 

* Weeks 3 and 4 have allocated significant time for right-side operations. Why do you expect these will take significant effort? Aren't they just reversals of left-side operations?

* You keep referencing a "format" method... I'm not aware of any format method on dict, set or frozenset. What are you referring to here?

**Comment by ad1269** [comment]
@freakboy3742 I’ve addressed your critiques below. Let me know if this is acceptable.

1. In retrospect, I didn’t really make this clear in the spec, but I was going to allocate two days for the implementation, testing, and documentation of each of the Set and FrozenSet methods. That way I complete all 5 functions in the 2 weeks specified. So for example during weeks 7 and 8, I would spend the first two days coding isdisjoint(), copy it into both the Set and FrozenSet classes, then write comprehensive tests for each class, making sure that FrozenSet preserves its immutability.

2. I’m sorry, I actually missed the fact that these would be just simple reverse implementations of current left side operations. I’ll amend my proposal in the near future to account for this.

3. I’m talking about the custom __format__ method that gets called for an object whenever we use the default python. “{}”.format(Object) method. Details can be found [here](https://docs.python.org/3/reference/datamodel.html#object.__format__). I need to research into the format specification mini language, and the details of how to implement format for each object.

**Comment by freakboy3742** [comment]
Unfortunately, this proposal wasn't accepted.
