### ISSUE TITLE
Gsoc proposal:update's and addon's on str and int

### ISSUE THREAD

**Issue by shyamsunder007** [pybee/voc#473]
Please, may know any modification's to be done and hoping for a quick and positive response
# **Task:**
Complete implementation of  str and int which includes some new math functions added to int  and it  also includes to correct all the checkstyle error’s in the whole project  and to write doc’s, test for all the function’s  in str and int
# **Success:**
All the method’s implementation will be completed for str and int ,and also in addition to that checkstyle error’s will be resolved and doc for every method in str,int will be written and at last some of the math functions will be added to int as long as time permits
# **Design Specifications:**
Initially I will l come to Str file in which there are 28 methods for which doc has not been written so I will complete that, after that I will be completing the rest 16 methods  implementation and I will schedule these during weeks based on their difficulty for example if I have to complete 2 complex and 3 easy to do in 2 weeks ,I will complete complex problems one in each week then I will solve easy problems  along with checking style errors and writing doc’s for the methods then  after solving them  I will come to int there  I will complete remaining methods first, then I will be going on adding some math functions like square of a number, hypo of a traingel,isSqure,isRightangled etc….

 **The Things which I need to Work on during Community Bonding Period as I feel them as Difficult to tackle**

Format:
Encode
Casefold
Translate
Rmul,rmod

 These methods  I fell difficult because some of them may  include  multiple arguments of different types ,so I need to work on it about how it works or how it should be done .so, it may consume 2 or 3 days for each of them and  along with solving them  some checkstyle error’s and also by writing doc’s for some methods or by correcting them and some of the methods involve learning various algorithms for their functionality. And some methods should be implemented efficiently,I will work upon these during community  bonding period also in order to get very good clarification and will start it after that as soon as possible.	
	
# **Timeline**
##  (Community Bonding Period)
•	Solving some check-style errors
•	Writing doc’s
•	Discussion above the complex problems on how to tackle it and clearing some doubts.
•	Participate in community discussions on Gitter, and other platforms
•	Get up to date on all documentation
##  (Week 1)
•	Work on str functions i.e rmul,rmod,maketrance
•	Clearing check-style errors
•	Writing doc’s and test’s 
##  (Week 2) 
•	Work on str functions i.e casefold
•	Clearing check-style errors
•	Writing doc’s and test’s 
## (Week 3) 
•	Work on str functions i.e encode
•	Clearing check-style errors
•	Writing doc’s and test’s 
##  (Week 4)
•	Work on str functions i.e format,formatmap
•	Clearing check-style errors
•	Writing doc’s and test’s 
## (Week 5) 
•	Work on str functions i.e isidentifier,isnumeric,isprinrable
•	Clearing check-style errors
•	Writing doc’s and test’s 
## (Week 6)
•	Work on str functions i.e rpartion,rsplit,splitlines
•	Clearing check-style errors
•	Writing doc’s and test’s 
##  (Week 7)
•	Work on str functions i.e strip,replace,translate
•	Clearing check-style errors
•	Writing doc’s and test’s 
## (Week 8)
•	Work on int  functions i.e radd,rsub,rmul,rtruediv,rfloordiv
•	Clearing check-style errors
•	Writing doc’s and test’s 
##  (Week 9) 
•	Work on int  functions i.e rlshift,rrshift,rdivmod,rpow,,rmod,
•	Clearing check-style errors
•	Writing doc’s and test’s 
## (Week 10)
•	Work on int  functions i.e rxor,ror,rand
•	Clearing check-style errors
•	Writing doc’s and test’s 
##  (Week 11)
•	Rest leftover can be used as a backup
•	If everything is completed then we can include new math functions in int
•	New math functions in math are like isSquare,isRectangle,isTraingle,isRightangled…etc
Two weeks left for backup and improvements
##  (Final Week)
•	Submit final work and mentor evaluation

**Comment by freakboy3742** [comment]
@shyamsunder007 Thanks for the application. Here's some feedback:

* It isn't clear why you consider rmod, rmul - or, for that matter, any of the right-side operations in weeks 6, 8, 9 or 10 to be "complex" operations. Aren't they just reversed invocations of existing left-hand operations?

* Of the operations you've listed as complex, "encode" is one that is particularly interesting. Yes, binary encoding is complex. But it's also something I'm fairly certain Java has built-in support for. Have you done any investigations beyond "I need to implement this"?

* Some of the operations you like (like strip and replace) look like they've already been implemented.

* The basis for your estimates on the math module are unclear. Won't most of these methods already have an implementation in `java.math`?

* "Clearing check-style errors" and "writing docs and tests" isn't something you need to repeat every week. It's an implied part of the software development process.

* You've essentially allocated 2-3 weeks as a contingency on a 12 week schedule. This doesn't give me very much confidence in your overall estimates.

**Comment by freakboy3742** [comment]
Perhaps you've missed the point of the scheduling process - its to *eliminate* unexpected factors. You've essentially *allowed* for a 25% slip in your schedule. If it's potentially 25% under, I have no reason to believe it won't be 25% *over*, either. The entire *reason* we ask for schedules is for you to do the research into what you don't understand so that we have confidence that *you* understand the problem you're proposing to solve.

As for check style errors... I don't know where you're getting 100 check style errors from - if there are any style problems, the build *will not pass* - and the build is currently passing fine.

**Comment by shyamsunder007** [comment]
Timeline

(Community Bonding Period)

•	Solving some check-style errors
•	Writing doc’s
•	Discussion above the complex problems on how to tackle it and clearing some doubts.
•	Participate in community discussions on Gitter, and other platforms
•	Get up to date on all documentation

(Week 1)

•	Work on str functions i.e rmul,rmod,maketrance
•	Clearing check-style errors
•	Writing doc’s and test’s

(Week 2)

•	Work on str functions i.e casefold

(Week 3)

•	Work on str functions i.e encode

(Week 4)

•	Work on str functions i.e format,formatmap


(Week 5)

•	Work on str functions i.e isidentifier,isnumeric,isprinrable,rpartion,rsplit,splitlines

Phase 1 Evaluation

(Week 6)

•	Work on str functions translate and add new funtion like isPalindrme,numberof words,nomberoflines


(Week 7)

•	Work on int  str functions  radd,rsub,rmul,rtruediv,rfloordiv,, radd,rsub,rmul,rtruediv,rfloordiv

(Week 8)

•	Work on int functions i.e rlshift,rrshift,rdivmodX, rxor,ror,rand

(Week 9)

•	Work on new int functions i.e isSquare(),IsPrime(),isEven(),isTraingle(),isEqualaterl,isIscoceles,isrightanle

Phase 2 Evaluation

(Week 10)

•	Work on new int functions i.e isPolygon,isClosedPolygon,isOpenPolygon,,areaOf Polygons

(Week 11)

•	Work on new int functions i.e slopeofLine(),trignometricFunctions,intercetionPointofStraightLine(),interseptsOfLin




(Week 12)

•	Rest leftover can be used as a backup
•	Solve checkstyle eroors
•	Write doc's for all the methods available in an easy way to understand



This is y brief updated timetable for my Gsoc Plan

**Comment by freakboy3742** [comment]
Unfortunately, this proposal wasn't accepted.
