### ISSUE TITLE
Failing test : tests.datatypes.test_str.BinaryStrOperationTests.test_add_None

### ISSUE THREAD

**Issue by amirhdrz** [pybee/voc#474]
Hi, I've been try to run the test suite, however I get over a 1000 failed test cases, most of which are test_str tests.

Description of my environment:
Windows 10 machine
Running tests while VOC virtualenv is activated.
`Python 3.4.4`
`javac 1.8.0_121`

```
======================================================================
FAIL: test_add_None (tests.datatypes.test_str.BinaryStrOperationTests)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "c:\users\amir\github\voc-dev\voc\tests\utils.py", line 790, in func
    substitutions=getattr(self, 'substitutions', SAMPLE_SUBSTITUTIONS)
  File "c:\users\amir\github\voc-dev\voc\tests\utils.py", line 829, in assertBinaryOperation
    run_in_function=False,
  File "c:\users\amir\github\voc-dev\voc\tests\utils.py", line 398, in assertCodeExecution
    self.assertEqual(java_out, py_out, context)
AssertionError: '>>> [365 chars]y\n\n>>> x = "Mÿ hôvèrçràft îß fû\u0142l öf éêl\u015b"\n[389 chars]==\n' != '>>> [365 chars]y\n\n<class \'UnicodeEncodeError\'> : \'charma[379 chars]==\n'
  >>> x = ""
  >>> y = None
  >>> x + y
  <class 'TypeError'> : Can't convert 'NoneType' object to str implicitly

  >>> x = "3"
  >>> y = None
  >>> x + y
  <class 'TypeError'> : Can't convert 'NoneType' object to str implicitly

  >>> x = "This is another string"
  >>> y = None
  >>> x + y
  <class 'TypeError'> : Can't convert 'NoneType' object to str implicitly

+ <class 'UnicodeEncodeError'> : 'charmap' codec can't encode character '\u0142' in position 28: character maps to <undefined>
- >>> x = "Mÿ hôvèrçràft îß fû\u0142l öf éêl\u015b"
- >>> y = None
- >>> x + y
- <class 'TypeError'> : Can't convert 'NoneType' object to str implicitly

  >>> x = "One arg: %s"
  >>> y = None
  >>> x + y
  <class 'TypeError'> : Can't convert 'NoneType' object to str implicitly

  >>> x = "Three args: %s | %s | %s"
  >>> y = None
  >>> x + y
  <class 'TypeError'> : Can't convert 'NoneType' object to str implicitly

  ===end of test===
 : Global context: Error running x + y

----------------------------------------------------------------------
Ran 1 test in 5.709s

FAILED (failures=1)
Test failed: <unittest.runner.TextTestResult run=1 errors=0 failures=1>
error: Test failed: <unittest.runner.TextTestResult run=1 errors=0 failures=1>
```

**Comment by freakboy3742** [comment]
This is definitely interesting... this failure isn't happening on our CI server.

Can you confirm:
(a) That this is happening on a clean checkout of VOC
(b) The git revision that you're using
(c) Anything else you can tell us about your Windows machine. Given that the failure is in str tests, and specifically around encoding issues, I'm wondering if there might be a language encoding issue. What language is your computer set to use?

**Comment by amirhdrz** [comment]
This seems to have been a console encoding issue on my machine.
Running following commands in the terminal solved the problem for me.
I can now pass the test successfully.

`chcp 65001`
`set PYTHONIOENCODING=utf-8`

**Comment by freakboy3742** [comment]
Good to know you've fixed this - Thanks for debugging it. 

Out of interest, is this the result of something unusual that you've done to your machine in the past, or is it a default configuration that many people will have on their machine? If it's likely to be a common problem, then it would be good to document how to diagnose and fix the problem so that others don't hit the same issue.

**Comment by amirhdrz** [comment]
My best guess is that the issue was caused by one of the many development programs I've installed recently, sorry I can't really pinpoint it further than that.

This issue also caused one of my python scripts that printed unicode characters to throw a similar error, which is how I found the fix for it. However, I didn't have any such problems before.
