### ISSUE TITLE
GSoC: Complete implementation of bool, int, float, and complex types and Partial implementation of math module

### ISSUE THREAD

**Issue by soandrew** [pybee/voc#475]
# Task
I want to complete the implementation of the `bool`, `int`, `float`, and `complex` data types, as well as start an implementation of the `math` module. 

# Success
100% completion of the `bool`, `int`, `float`, and `complex` data types as indicated by no more methods throwing a `NotImplementedError`.
75% completion of the `math` module (37 of the 49 methods/constants as listed from the [Python docs](https://docs.python.org/3/library/math.html)).

# Details
## Data types
For each type I will work on writing code (including any documentation and test cases as needed) for any methods marked with the `NotImplementedError`

At the time of this writing, the following methods are unimplemented:

  - For all data types:
    - Reverse methods:
      - `radd`, `rsub`, `rmul`, `rtruediv`, `rfloordiv`, `rmod`, `rdivmod`, `rpow`
      - `rlshift`, `rrshift`, `rand`, `rxor`, `ror` (unsupported for `float`)
    - `format` and `dir`
  - For `int`:
    - `int()` with a base
  - For `float`:
    - `mul`, `pow()` with modulo, `round()` with ndigits
  - For `complex`:
    - `byValue`, `bool`, `float`

I believe that implementing the reverse methods should simply involve calling the forward version of the method, and implementing all 47 of them should not take more than a week.

The 7 type specific methods (`int()`, `mul`, `pow()`, `round()`, `byValue`, `bool`, `float`) are fairly simple, and each should not take more than a day to implement.

Finally the `format` and `dir` methods are the more complicated functions and will require a bit more research in Python's [Format Specification Mini-Language](https://docs.python.org/3/library/string.html#formatspec) compared to [Java's Format String Syntax](https://docs.oracle.com/javase/7/docs/api/java/util/Formatter.html#syntax), as well as Python Attributes. I anticipate that fully completing these two methods for each data type will take 3 to 4 weeks.

## `math` module
For the `math` module, of the 49 methods/constants that need to be implemented, I believe that 25 of them can be [implemented directly](https://docs.oracle.com/javase/8/docs/api/java/lang/Math.html) using the `java.lang.Math class`. In addition to those 25, I plan to implement 12 more.

Implementation planned for the math module:

  - 24 methods/constants that can be directly taken from `java.lang.Math`
    - `ceil`, `copysign`, `fabs`, `floor`
    - `exp`, `expm1`, `log1p`, `log10`, `pow`, `sqrt`
    - `acos`, `asin`, `atan`, `atan2`, `cos`, `hypot`, `sin`, `tan`
    - `degrees`, `radians`
    - `cosh`, `sinh`, `tanh`
    - `pi`, `e`
  - 12 methods/constants that are not as straight forward
    - `factorial`
    - `isfinite`, `isinf`, `isnan`
    - `log`, `log2`
    - `acosh`, `asinh`, `atanh`
    - `tau`, `inf`, `nan`

Implementing the 24 methods/constants from the Java `Math` class should not be hard at all. I anticipate taking at most a week for these.

The 3 constants (`tau`, `inf`, `nan`) and the 3 Boolean methods (`isfinite`, `isinf`, `isnan`) should be straight forward to implement, taking perhaps a week for all 6.

The logarithmic methods will be a bit more complex. The Java `Math` class does provide a natural log function, but Python's log function additionally supports a base argument. However, the formula to convert is simple so this will take only 1 or 2 days.

The inverse hyperbolic methods can be expressed in terms of logarithms so these should not take more than 1 or 2 days to implement.

Finally the `factorial` method I anticipate to be fairly complex to implement. Naïve recursive or iterative factorial algorithms are easy, but are not efficient. This will require research into the divide and conquer algorithm that Python uses, and I anticipate this will take about a week.

# Schedule
## Community Bonding: May 4 – 30
  - Get involved with discussions on Gitter
  - Investigate how binary operation test cases are handled
  - Investigate how Python attributes have been implemented
  - Investigate how modules are to be implemented and where test cases for these should go

## Week 1: May 30 – June 2
  - Implement the reverse methods for `bool`, `int`, `float`, and `complex`

## Week 2: June 5 – 9
  - Implement `int` method `int()` with a base
  - Implement `complex` methods `byValue`, `bool`, and `float`

## Week 3: June 12 – 16
  - Implement `float` methods `mul`, `pow()` with modulo, and `round()` with ndigits

## Week 4: June 19 – 23
  - Implement `format` method for `bool` and `int`

## Week 5: June 26 – 30
  -  Implement `format` method for `float` and `complex`

## Week 6: July 3 – 7
  - Implement `dir` method for `bool` and `int`

## Week 7: July 10 – 14
  - Implement `dir` method for `float`, and `complex`

## Week 8: July 17 – 21
  - Implement the 24 math methods/constants described above that can be taken directly from the Java `Math` class

## Week 9: July 24 – 28
  - Implement `math` constants `tau`, `inf`, and `nan`
  - Implement `math` methods `isfinite`, `isinf`, `isnan`

## Week 10: July 31 – Aug 4
  - Implement `math` methods `log`, `log2`

## Week 11: Aug 7 – 11
  - Implement `math` methods `acosh`, `asinh`, `atanh`

## Week 12: Aug 14 – 18
  - Implement `math` method `factorial`

**Comment by freakboy3742** [comment]
This is a solid proposal. 

It's an ambitious collection of work, but your reasoning for assertion is sound - as long as you can back up your level of productivity. The best way I can think of do this is to point at examples of pull requests that you've had accepted, with estimates of how long each one took.

**Comment by soandrew** [comment]
Thanks for the kind words and advice. I've been working on a 'Details about myself" section for the official project proposal and will be sure to include information such as my programming background and experiences including past pull requests.

**Comment by soandrew** [comment]
@freakboy3742 Another coder seems to have already been working quite extensively on the `math` module here #494. I'm wondering if it would be appropriate to implement the `cmath` module as a part of my proposal instead of the `math` module as originally planned? 

It has fewer functions (30), but the Java Math class does not support complex numbers directly so the implementation will be more difficult. However it is still doable utilizing many of the elementary functions available so I believe it should take about the same time frame to implement.

**Comment by freakboy3742** [comment]
Unfortunately, this proposal wasn't accepted.
