### ISSUE TITLE
GSOC: Complete implementation of time and io module.

### ISSUE THREAD

**Issue by deep110** [pybee/voc#476]
### **BASIC INFORMATION**

* **Name:** Deepankar Agrawal
* **Email:** deepankar11093@gmail.com
* **Phone Number:** +91 8791286328
* **Github/ Gitter Chat Room:** [deep110](https://www.github.com/deep110)
* **Skype:** live:deepankar11093
* **University:** Indian Institute of Technology, Roorkee.
* **Field of Study:** Electronics And Communication Engineering (Batch of 2017)

### **PROJECT INTRODUCTION**

VOC currently lacks implementation of time and io module, for which CPython heavily depends on C Api’s. I think implementing these low-level modules is a crucial step in further expansion of voc functionality. 
The success includes 100% implementation of time and 80% of io module.

### **PRE-GSOC INVOLVEMENTS**

Here is a [list](https://github.com/pybee/voc/pulls?q=is%3Apr+author%3Adeep110) of my PRs made so far (All merged) : - 
* [#498](https://github.com/pybee/voc/pull/498)**:** (not merged yet) Implement some methods for Set 
* [#401](https://github.com/pybee/voc/pull/401)**:** fix issue list comprehensions causes runtime crash
* [#400](https://github.com/pybee/voc/pull/400)**:** fix issue#362 Setting instance attributes
* [#391](https://github.com/pybee/voc/pull/391)**:** Implements some methods for dict
* [#379](https://github.com/pybee/voc/pull/379)**:** Fix AttributeError for complex.real and complex.image
* [#371](https://github.com/pybee/voc/pull/371)**:** Adds some method implementation for Complex type

### **DESIGN SPECIFICATIONS**

**TIME:**

The time module have 26 functions to implement, which I have mainly classified in two groups - Easy (less likely to present problem) and Complex (more research required). 

Complex (12 functions):-

* **time**.**daylight**, **time.altzone**, **etc**. depend on DST timezone and quoting from python docs - "*DST rules are magic (determined by local law) and can change from year to year. The C library has a table containing the local rules (often it is read from a system file for flexibility) and is the only source of True Wisdom in this respect.*" 
So I need to find similar API in JAVA. Though I know this that Java has support for DST as       it is given in oracle [docs](http://www.oracle.com/technetwork/java/javase/timezones-137583.html#intro). I think *TimeZone* Api, but not sure.

* **time**.**tzset** is only available in unix, and resets the time-zone to the one specified in environment variable "TZ".

* Some of the new methods added in Python3.3 specifically for unix like **time.clock_getres(clk_id), time.clock_gettime(clk_id), etc.** can return time for specific clockId.

* CLOCK_HIGHRES, CLOCK_MONOTONIC_RAW etc. are hardware specific clock times, like for Solaris OS and Linux 2.6.28 and later respectively. Need to dig deeper for their Java Api’s.

Easy:-

* Rest all the functions seems easy to implement.

**IO:**

This module is a big one and will consume major part of my gsoc time. The io in python is divided into three types:-

1. Text I/O
2. Binary I/O
3. Raw I/O

First I will implement TextIO. It requires minimum base implementation of IOBase, TextIOBase, RawIOBase, BufferedIOBase, TextIOWrapper, BytesIO and StringIO.

* **IOBase** is mainly an abstract class and mainly have close(), closed, flush(), fileno(), isatty(), flush(), readable(), seek(), seekable, tell(), truncate(), writable(), writelines() raising **UnSupportedOperation**. Only methods implemented are readline() and readlines().

* **RawIOBase** implements read() and readall(). It returns unsupported for readinto() and write(). TextIO in python is not thread safe. Since its implementation is usually for low level sequential bytes, *java.nio.ByteBuffer* would be better suited than streams and it is also non-blocking.

* **BufferedIOBase** implements read() and readinto() of IOBase and adds a new abstract method - detach().

* **TextIOBase** uses BufferedIOBase as underlying buffer and adds implementation to some functions of IOBase like *read, readinto, detach, readline, seek, tell, write* and add new ones like encoding, newlines. But mainly it is still a abstract class.

* **TextIOWrapper** inherits from TextIOBase. It provides implementation for all IOBase abstract methods and adds one new line_buffering.

* **BytesIO** inherits from BufferedIOBase and implement its methods. Apart from that it introduces three new methods -> *getbuffer, getvalue, read1*. The buffer here is nothing but byteArray. 

* **StringIO** is mainly a entry module for TextIO and inherits from TextIOWrapper. It’s just a wrapper on TextIOWrapper with just one method to implement *getvalue* and uses **BytesIO** as underlying in memory buffer.

Next I will proceed to the implementation of Binary I/O. It provides BytesIO(already implemented), BufferedReader, BufferedWriter, BufferedRandom, BufferedRWPair. 

* **BufferedIOMixin** is a mixin implementation of BufferedIOBase with an underlying raw stream. It is helper class for BufferedReader and Writer.

* **BufferedReader** inherits from BufferedIOMixin. In addition to methods of BufferedIOBase it adds implementation for peak(size), read([size]), read1(size).

* **BufferedWriter** inherits from BufferedIOMixin. In addition to methods of BufferedIOBase it adds implementation for flush(), write(b).

* **BufferedRWPair** is just a wrapper for both reader and writer and implements all method of BufferedIOBase except detach.

* **BufferedRandom** inherits from both BufferedReader and BufferedWriter and further supports seek() and tell(),

For implementation details of io module I will be following CPython’s **_pyio.py** module and of course python docs. java.io is complex enough to be incorporated into python io. Though Java has alternate IO Api's [**java.nio**](https://docs.oracle.com/javase/7/docs/api/java/nio/ByteBuffer.html) which have support for bytes and byteArrays like python. It has been used in [Jython3](https://github.com/jython/jython3/tree/master/src/org/python/core/io). I have gone thru that code and I think various parts of that code can be reused here.

**Concerns for Android Support:** I will be mainly using java.nio.ByteBuffer, java.nio.Channels and sometimes java.nio.CharBuffer or IntBuffer, and their implementation exists in Android.
https://developer.android.com/reference/java/nio/package-summary.html
In FileIO, java.nio.FileChannel will be used which is also present. The only thing that is absent is java.nio.file.Files, which is just a utility class that consists exclusively of static methods that operate on files, directories, or other types of files, which can be taken easily from Java source [code](http://grepcode.com/file/repository.grepcode.com/java/root/jdk/openjdk/8-b132/java/nio/file/Files.java).
So I think support on Android would not be an issue.

### **TIMELINE**

**May 4-May 30 (Community Bonding Period)**

* Participate in community discussions on Gitter, and other platforms
* Delve into research of complex functions of time and io module.
* Since I am already familiar with most of codebase, I will implement some functions of ByteArray which may be required for io module.

**May 30-June 2 (Week 1)**

* Implement time.struct_time (tuple), as it will be holder for time value sequence returned by gmtime(), localtime(), etc.
* Implement gmtime(), localtime(), asctime()
* Implement, ctime(), mktime()

**June 5-9 (Week 2)**

* Implement daylight(), altzone() [DST]
* timezone, tzname

**June 12-16 (Week 3)**

* Implement, strftime (will take time, as convert time tuple into formatted string)
* Implement strptime (inverse of above)

**June 19-23 (Week 4)**

* Implement clock_getres(clk_id), clock_gettime(clk_id), clock_setres(clk_id)
* Implement perf_counter, process_time.
* Hardware specific [Either can be done or not] -> CLOCK_HIGHRES, CLOCK_MONOTONIC, CLOCK_MONOTONIC_RAW, CLOCK_PROCESS_CPUTIME_ID, CLOCK_REALTIME, CLOCK_THREAD_CPUTIME_ID

**June 26-30 (Week 5)**

* Implement IOBase methods.
* Implement RawIOBase and BufferedIOBase.

**Phase 1 Evaluation due June 30**

**July 3-7 (Week 6)**

* Implement TextIOBase. (Will not take much time)
* Start implementing TextIOWrapper. Functions implementing this week are, __init__, encoding, errors, line_buffering, buffer, seekable, readable, writable, flush, close, closed.

**July 10-14 (Week 7)**

* Continue with TextIOWrapper. Rest of the functions will be implemented this week-> name, isatty, write, tell, truncate, detach, seek, read, readlines, new_lines. 

**July 17-21 (Week 8)**

* Implement BytesIO.
* Functions are __init__, getvalue, getbuffer, close, read, read1, write, seek, truncate, readable, writeable, seekable.

**July 24-28 (Week 9)**

* Finish StringIO by implementing -> init, getvalue, repr, encoding, detach.
* Test and document TextIO.

**Phase 2 Evaluation due July 28**

**July 31-August 4 (Week 10)**

* Implement BufferedIOMixin’s functions seek, tell, truncate, flush, close, detach, closed, isatty, __repr__, fileno.
* Implement BufferedReader functions as many as possible -> __init__, readable, read, peek, read1, tell, seek.

**August 7-11 (Week 11)**

* Complete BufferedReader implementation of the functions left.
* Implement BufferedWriter -> __init__, writeable, write, truncate, flush, tell, seek

**August 14-18 (Week 12)**

* Implement BufferedRWPair  and BufferedRandom.

**August 21-29 (Final Week)**

* Write the pending docs or test if any.
* Submit final work and mentor evaluation.

**Wishlist: If work gets completed before time, also desired to be taken up post GSoC.**
* Implement FileIO.

### **ABOUT ME**
I am a 22 year old, fourth year student currently enrolled in ECE (IV Year Course) at IIT Roorkee. I’ve had a strong passion for programming and mobile development since my freshman year. I am president of Mobile Development Group ([MDG](https://mdg.sdslabs.co/)) at IIT Roorkee, which just consists of a bunch of passionate enthusiasts fostering technical activities in the campus. We also have an active open source contribution activity on [github](https://github.com/sdsmdg/) and develop apps and games for campus as well as for general audience.

**SKILLS**
* Programming Languages: Java, Python, C#, JavaScript
* Interests: Android App Development, GameDev.

**MY PROJECTS**
* **JMusic:** A minified and light-weight audio processing library written in Java that is compatible with android. It is currently under development and code can be found [here](https://github.com/sdsmdg/JMusic).
* **FlashDict:** A chrome extension that gives you instant meaning of the work that is double clicked. GitHub link:- https://github.com/deep110/FlashDict
* **Androable:** Android library for connecting multiple devices over bluetooth. Github Link:- https://github.com/sdsmdg/Androble
* I have also made some games like [Ballx2](https://github.com/deep110/Ball-x2)(Also on [playstore](https://play.google.com/store/apps/details?id=com.mdg.ballx2)), [ZombieHunt](https://github.com/deep110/ZombieHunt) and [BadBlood](https://github.com/deep110/BadBlood) (Xbox-game).

I have no other involvements this summer and can easily work for 40+ hours per week. Also I plan to maintain daily logs so that my mentor can easily track my progress.

Looking forward for feedbacks.

**Comment by freakboy3742** [comment]
This is a fairly good breakdown of the work you're going to tackle from a Python perspective; however, you've given very little indication how this maps onto the underlying Java APIs. It's difficult to have confidence in your time estimates if you haven't given details of how you arrived at them. For example, if it turns out that Java's IO model (which is fairly complex) doesn't map well to Python's API, then saying you're going to finish X features in a week isn't especially meaningful.

**Comment by deep110** [comment]
@freakboy3742 Thanks for the feedback.
Yes, java.io is complex enough to be incorporated into python io. Though Java has alternate IO Api's **java.nio** which have support for bytes and byteArrays like python. It has been used in [Jython3](https://github.com/jython/jython3/tree/master/src/org/python/core/io). I have gone thru that source and various parts of that code can be reused here.
Also, should I also add various snippets of code, if it's required. Thanks!!

**Comment by freakboy3742** [comment]
Before you get too enthused about java.nio, you might want to check the support on Android. Android doesn't have a full nio implementation.

**Comment by deep110** [comment]
@freakboy3742 I will be mainly using java.nio.ByteBuffer and sometimes java.nio.CharBuffer or IntBuffer, and their implementation exists in Android.
https://developer.android.com/reference/java/nio/package-summary.html

**Comment by deep110** [comment]
@freakboy3742 Hi, I have updated the proposal with my info, as well as with the concerns raised by you. Could you please give a quick feedback about it (means any updates or any additions or deletions to be made, timeline concerns), since the date of submission is getting closer.
Thanks in Advance.

**Comment by freakboy3742** [comment]
Unfortunately, this proposal wasn't accepted.
