### ISSUE TITLE
GSoC 2017 Proposal : Complete implementation of cmath,httplib and itertools module

### ISSUE THREAD

**Issue by dibyadas** [pybee/voc#479]
# Google Summer of Code 2017 Application Proposal
### 1. [About Me](#me)
<ul><li>Basic Information
<li> Background work and Programming Skills</ul>

### 2. [The Project](#project)
<ul> <li> The problem and the motivation
<li> The plan
<li>Current Workings</ul>

### 5. [References](#refs)
<a name="me" /> </a>
 About Me
========
### Basic Information
* Name : Dibya Prakash Das
* University  : [Indian Institute of Technology, Kharagpur](https://iitkgp.ac.in)
* Degree  : Int M.Sc in Mathematics and Computing
* Email  : dibyadas998@gmail.com
* Github  : @dibyadas
* gitter(pybee) handle : @dibyadas
* Timezone  : IST (UTC +5:30)

### Background work and Programming Skills
I am a first year undergraduate student at the Indian Institute of Technology , Kharagpur. I am enrolled in its 5 year Mathematics and Computing course.
I work on Linux Mint 18 with Sublime Text as my primary text editor. I like to use Sublime for its powerful and flexible features. I am proficient in Python , C and Java.
I love Python because it’s dynamic and I don’t have to worry about problems I usually face with other languages.
I used Java in my School and was introduced to Object Oriented Programming Principles through it.
I know how to use Git and Github. And whenever I am stuck , I google and always come back with a solution.

<a name="project" /> </a>
The Project
==================
### The Problem and the Motivation

VOC is software that compiles Python code directly into Java Bytecode all ready to run.
As of now, VOC works for very simple and basic programs. There are some builtin functions and features that have not been implemented. In Python everything is an object. It is an dynamically typed language. VOC uses the python’s Abstract Syntax Tree feature to achieve its goals.

VOC currently has limited python standard library support.Namely, sys, os, types,time have been partially implemented. But good deal of important features are still missing.

I plan to implement the cmath module.Jython module for cmath exists and can be easily ported to VOC with some minor changes.
During the GSoC period I plan to successfully complete the 100% implementation of the http.client module and 70% itertools module.

# http.client

The httplib is also an important module. If successfully implemented, it can really increase the usability of VOC . The httplib has been renamed to http.client in Python3 . Implementing it would not be that hard too, considering that there are Java packages like Apache HTTP client and java.net.* out there. 
The classes present in this module is :- 
<ol><li>1.HTTPConnection</li>
<li>2.HTTPResponse</li>
<li>3.HTTPSConnection -> It is a subclass of the HTTPConnection</li>
<li>4.HTTPException -> It is the base class of all other exceptions raised by this module and is itself derived from Python's Exception class :-</li>
    <ol><li>1.Not Connected </li>
    <li>2.InvalidURL </li>
    <li>3.UnknownProtocol </li>
    <li>4.UnknownTransferEncoding </li>
    <li>5.UnimplementedFileMode</li>
    <li>6.IncompleteRead</li>
    <li>7.ImproperConnectionState</li>
    <li>8.CannotSendRequest</li>
    <li>9.CannotSendHeader</li>
    <li>10.ResponseNotReady</li>
    <li>11.BadStatusLine</li>
    <li>12.LineTooLong</li></ol>
<li>5.And about 50 constants for the status codes of the http request response</li></ol>
Here is a small example program of how to use the java.net.HttpURLConnection and javax.net.ssl.HttpsURLConnection to send HTTP requests :- 
 
```
import java.net.HttpURLConnection;
import java.net.URL;
import javax.net.ssl.HttpsURLConnection;

// For sending GET request- 

private void sendGet() throws Exception {
        String url = "http://www.google.com/search?q=voc";
        URL obj = new URL(url);
        HttpURLConnection con = (HttpURLConnection) obj.openConnection();

        con.setRequestMethod("GET"); //setting the request method

        con.setRequestProperty("User-Agent", USER_AGENT); /* setting the request property */

        int responseCode = con.getResponseCode(); /* the part where the connection to the specified HTTP address is done and the response code is stored. */
        System.out.println("Response Code : " + responseCode);
        BufferedReader in = new BufferedReader(
                new InputStreamReader(con.getInputStream())); 
        String inputLine;
        StringBuffer response = new StringBuffer();
        while ((inputLine = in.readLine()) != null) {
            response.append(inputLine);
        }
        in.close();
    }

// For sending the POST request-

private void sendPost() throws Exception {

        String url = "https://selfsolve.apple.com/wcResults.do";
        URL obj = new URL(url);
        HttpsURLConnection con = (HttpsURLConnection) obj.openConnection();

        con.setRequestMethod("POST"); //setting the request method
        con.setRequestProperty("User-Agent", USER_AGENT);
        con.setRequestProperty("Accept-Language", "en-US,en;q=0.5");

        String urlParameters = "sn=C02G8416DRJM&cn=&locale=&caller=&num=12345"; 

        // Send post request
        con.setDoOutput(true);
        DataOutputStream wr = new DataOutputStream(con.getOutputStream());
        wr.writeBytes(urlParameters);
        wr.flush();
        wr.close();

        int responseCode = con.getResponseCode();

        // System.out.println("Response Code : " + responseCode);

        BufferedReader in = new BufferedReader(
                new InputStreamReader(con.getInputStream()));
        String inputLine;
        StringBuffer response = new StringBuffer();

        while ((inputLine = in.readLine()) != null) {
            response.append(inputLine);
        }
        in.close();

    }
```
This is an example of the structure I have in my mind to implement the module in VOC

```
package python.httpclient;

// necessary java libraries imported here

import org,python.Object;
import java.net.HttpURLConnection;
import java.net.URL;
import javax.net.ssl.HttpsURLConnection;

public class __init__ extends org.python.types.Module {
    public __init__(){
        super();
    }
}

public class HTTPConnection{

    public HTTPConnection(Object host,Object port,Object timeout,Object source_address){}

    public Object request(Object method,Object url,Object body,Object headers){
    }

    public httpclient.HTTPResponse getresponse(){
        return new httpclient.HTTPResponse(/* making a response and returning it */);
    }
    //... 
    //... 
    //... 
}

public class HTTPResponse{ 
    public HTTPResponse(HTTPConnection v){
    }

    public Object read(Object amt){ // optional argument amt
    }

    public List getheaders(){
        // returns a list of (header,value) tuples 
    }
    //...
    //...
    //...
}

public class HTTPSConnection extends HTTPConnection { // subclass of HTTPConnection to handle communication with secure servers

}

public class HTTPException extend org,python.types.Exceptions {
}

public class NotConnected extends HTTPConnection {
}
// and other exception classes
```

Here are some resources that I plan to follow while implementing this module.
1. http://stackoverflow.com/questions/2793150/using-java-net-urlconnection-to-fire-and-handle-http-requests<br>
2. http://www.journaldev.com/7148/java-httpurlconnection-example-java-http-request-get-post<br>
3. http://www.java2blog.com/2016/07/how-to-send-http-request-getpost-in-java.html
4. http://www.bogotobogo.com/python/python_http_web_services.php

Extensive use of the these packages will be done to achieve this.
Package java.net :-
<ol><li>1. HttpURLConnection</li>
    <li>2. URLConnection</li>
<li>and javax.net.ssl.HttpsURLConnection</li></ol>

These functions can be wrapped in a java class for the http.client module for behaving like the HTTPConnection and HTTPResponse object. Also relevant exceptions will be raised for different errors.

# itertools

The `itertools` is an important module for iterator algebra. It has fast and efficient algorithms designed to handle iteration based problems. Implementing it will be trickier but doable. Jython modules for the same can be referred to while writing the code in VOC. Itertools has about 19 functions be divided into three categories.
Infinite iterators, Iterators terminating on the shortest input sequence and combinatoric generators. This will require some work and research to implement them. While most of the module is implemented in Jython. It can be directly ported to VOC with some minor changes.

I also plan to write and improve the existing documentation of VOC.
The documentation currently does not have any tutorial on how VOC uses the python’s AST to generate the Java bytecode. I believe it is an important part of the development process and deserves a tutorial. It will help to build a clear understanding of the internal working of VOC. A tutorial on the Java bytecode and AST from the VOC’s point of view is necessary in my opinion. The result of this will be that anyone who wants to contribute to VOC would not face a lot of difficulties while learning about this project. The documentation also has to be written in such a way so that people would not find it intimidating.

### The Plan

All in all, my work can be summed up as :-

1. **Implement the builtin cmath module.**

2. **Implementing itertools and httplib.** 
* For implementing httplib, there exists Java packages, like I mentioned earlier,which can be reused. It can take some time but is doable.
* Implementing itertools module. It has a lot mathematical   operations like permutations and combinations, in addition to Infinite iterators and Combinatoric generators.

3. **Writing and improving the existing VOC documentation.**
* Writing the documentation would not be complex at all, since I have acquired an almost clear understanding of the Python AST and Java bytecode. It will just take some time to complete.

### Current Workings

1. **Python math module implementation complete (open) [PR#494](https://github.com/pybee/voc/pull/494)**
Python math module completed, ready for review

2. **\_\_mul\_\_ function now working for the Str type and Int type (open) [PR#398](https://github.com/pybee/voc/pull/398)**
This PR led to further discussions with **cflee** about the underlying aspects.

3. **Derived class doesn't inherit some magic(dunder) methods from the parent class. (open) [Issue#436](https://github.com/pybee/voc/issues/436)**
I opened a ticket about a bug that I came across in VOC. Those dunder method referred here are all the Binary operations methods like 
\_\_mul\_\_() , \_\_sub\_\_() , when invoked as a*b ( for \_\_mul\_\_)

4. **[WIP] Fix issue #436 (closed) [PR#467](https://github.com/pybee/voc/pull/467)**
Opened a PR , fixing the above issue [#436](https://github.com/pybee/voc/pull/436). This still need discussions. I tried to modify the BinOp node to a call node , so now the code a*b will be translated to a.\_\_mul\_\_(). 
**freakboy3742** mentioned that this is not the correct way to solve this.

5. **[WIP] Fix issue #352 (open) [PR#470](https://github.com/pybee/voc/pull/470)**
In this PR , I tried to solve the issue [#352](https://github.com/pybee/voc/issues/352) opened by **eliasdorneles**. This deals with Exceptions. Raising Errors with custom arguments caused java NullPointerException.
I tried to solve the issue by modifying the bytecode generated by VOC when it sees a Raise Node.

6. **Minor Fix in README (merged) [PR#436](https://github.com/pybee/voc/issues/436)**
While going through the changes that VOC has undergone, I came across that lambda feature has been implemented by **adamrk** . The code that implemented this feature gave me a good understanding of how VOC generates the Java bytecode.

<a name="timeline" /> </a>
### Goal : Community bonding
* The principle focus in this period would be to thoroughly understand the  working of VOC and the Java opcodes, while I have understood most of it , I still need to clear some parts of it.
* Researching even further to implement the http.client module and the itertools module

### Goal : Complete Implementation of cmath	
* Writing tests for the newly implemented features of the cmath module.
* This can be easily completed within 2 weeks by using the jython cmath module.

### Goal : Implementation of the http.client module should be started.
* Working on the **HTTPConnection** class.
* Functions include :- `request()` and `connect()`. `request()` is a big function which can take a bit of time.
* Begin working on the **HTTPResponse** class

## Phase 1 Evaluation ( June 26 – June 30)
* The documentation for the implemented features should be complete.	
* Fixing any bugs that arise.

### Goal: Partially complete Implement of http.client module	
* Function include :- `getresponse()` , `close()` , `putrequest()` , `putheaders()` , `endheaders()` , `send()`
* By the end of week 6,in httplib module **HTTPConnection** should be 100% done while **HTTPResponse** should be done as much as possible. 		
* Implementation of these two classes should be complete using the standard library java.net.* 	

### Goal : Complete the implementation of **HTTPResponse** class
* **HTTPResponse** should be 100% done 	
* Functions include :- `read()` ,`getheader()` ,`getheaders()`
* Work on **HTTPSConnection** will be started. It is mostly similar to HTTPConnection.

## Phase 2 Evaluation ( July 24 – July 28 )
* Writing documentation for the implemented modules
* Fixing any bugs that arise.

### Goal : Complete the implementation of http.client module.
* The http.client module should be completed by completing the exception class of http.client.
* Work on porting the itertools module should be started and will be complete as much as possible.

### Goal : Writing and improving the development documentation of VOC	
* A week of this period will be used for the itertools module.
* And alongwith it, tests will be written for the implemented features so far.
* Also in this period, I will write tutorials for Python’s AST and Java Opcodes and include it in the documentation of VOC.

## Final Evaluation ( August 21 – August 290
* Writing summary of the project work done.

<a name="notes" /> </a>
## Notes	
* I have no commitment during summer, hence I can dedicate the required 	amount of time to the project.
* This is my first Google summer of Code experience and I am extremely enthusiastic about it, so I will work with full force to meet the proposed goals.
* I would love to keep contributing in this project in the future as well.
<a name="refs" /> </a>
## References
1. java.net.* package : https://docs.oracle.com/javase/7/docs/api/java/net/package-summary.html	
2. Python http.client module : https://docs.python.org/3.4/library/http.client.html	
3. Python itertools module : https://docs.python.org/3.4/library/itertools.html
4. VOC documentation : https://voc.readthedocs.io/en/latest/index.htm
5. Python cmath module : https://docs.python.org/3.4/library/cmath.html#module-cmath

**Comment by dibyadas** [comment]
@freakboy3742 Looking forward to your suggestions for improving my proposal

**Comment by freakboy3742** [comment]
This seems *extremely* optimistic as a timeline. You're proposing to implement *all* remaining data types, and *4* builtin modules. While I appreciate the enthusiasm, it doesn't seem realistic at all. 

But more importantly - this proposal gives me no reason to believe your estimates. You say it will take 2 weeks to finish *all* the data types. I've been working on VOC for *18 months* - admittedly, in a part time capacity, but still - I've spent more than 2 working weeks on it in total, and it feels like a lot more than 2 weeks work to *me* - and I'm an expert on the subject matter. 

You even flag that you haven't done a lot of research - you say you will be asking for "guidance from my mentor on the implementation of the modules itertools and httplib". The purpose of this proposal is to convince *us* that you know how to implement these modules - or, at least that you've got enough of a handle on the topic that the advice you're going to need is more about style and process, than "how do I do this?".

I think you need to spend a bit more time working on this proposal and backing up your extremely optimistic timelines. If it turns out you really are this productive, and you *are* able to do this much work - that's fantastic - but remember:

1. We're looking for quality, not quantity

2. The onus is on you to convince *us* that you can meet this schedule.

**Comment by dibyadas** [comment]
@freakboy3742 Thanks a lot for reviewing my proposal and for your valuable feedback. I will update this proposal keeping in mind the points you have mentioned. It seems I have underestimated the task the I have proposed to do. 
And you were right when you said that I will be asking for the style and the process and not a complete walkthrough on how to implement the modules.
Now that you have mentioned it that implementing 4 modules will be time consuming, do you think I should remove `itertools` module from my proposal?

**Comment by dibyadas** [comment]
@freakboy3742 I have updated my proposals. As the deadline is today, I would be grateful if you can share your final thoughts on this.

**Comment by freakboy3742** [comment]
Unfortunately, this proposal wasn't accepted.
