### ISSUE TITLE
GSoC 2017: Implementation on Builtin datatypes, optimizations and standard libs.

### ISSUE THREAD

**Issue by AdilsonTorres** [pybee/voc#482]
# Proposal for GSoC 2017

## Proposal
In this GSoC 2017, I plan to work on VOC projetct, completing the implementations on **builtins datatypes** (str, int, complex, etc.), optimizations on code paths for some data types (and where possible) and some standard libs (functools, enum, re, argparse). 

## Success
1. Bultins data types (str, int, bool, float, dict, etc.) finish.
2. Optimization on code paths for some data types.
3. stdlibs (functoots, enum, re and argparse).

## Details
I plan to work initially on builtin datatyes, finish with are already started and complete what is missing. After that look for optimizations related on code paths for some data types and other possibles places. When these things have been done, start working with stdlib in a order that doesn't depend much on a previous stdlib.

## Timeline

* **Week 1 (May 30 - June 2)**
  * Complete implementation on Str, Int, Bool, Float and Dict types.
  * Verify about now-passing expected failure tests (#462).
  * Also verify related tests and possible bugs with different versions of Python/OS Systems.
* **Week 2 (June 5 - 9)**
  * Complete implementation on Tuple, Slice, Set, Frozenset, Complex and List types.
  * Also verify related tests and possible bugs with different versions of Python/OS Systems.
* **Week 3 (June 12 - 16)**
  * Complete implementation on Range, Bytes, ByteArray and other types that may be misses.
  * Also verify related tests and possible bugs with different versions of Python/OS Systems.
* **Week 4 (June 19 - 23)**
  * Implement optimizations (#75) where type information is available for parameters. And look for others possible optimizations.
  * Also verify related tests and possible bugs with different versions of Python/OS Systems.
* **Week 5 (June 26 - 30)**
  * Finish possibles builtin types that are not implemented and their respective optimizations.
  * Also verify related tests and possible bugs with different versions of Python/OS Systems.
* **Week 6 (July 3 - 7)**
  * Verify if there is something miss on Sys stdlib.
  * Start to work with functools stdlib.
  * Also verify related tests and possible bugs with different versions of Python/OS Systems.
* **Week 7 (July 10 - 14)**
  * Finish functools stdlib.
  * Start to work with enum stdlib.
  * Also verify related tests and possible bugs with different versions of Python/OS Systems.
* **Week 8 (July 17 - 21)**
  * Finish enum stdlib.
  * Verify if there is something miss on functools, enum stdlibs.
  * Also verify related tests and possible bugs with different versions of Python/OS Systems.
* **Week 9 (July 24 - 28)**
  * Start to work with re stdlib and their related libs (sre_compile, sre_parse).
  * Also verify related tests and possible bugs with different versions of Python/OS Systems. 
* **Week 10 (August 31 - August 4)**
  * Continue to work with re stdlib and their related libs (sre_compile, sre_parse).
  * Also verify related tests and possible bugs with different versions of Python/OS Systems. 
* **Week 11 (August 7 - 11)**
  * Finish re stdlib.
  * Start to work with argparse stdlib and their related lib (textwrap).
  * Also verify related tests and possible bugs with different versions of Python/OS Systems. 
* **Week 12 (August 14 - 18)**
  * Finish argparse stdlib and their related lib (textwrap).
  * Also verify related tests and possible bugs with different versions of Python/OS Systems. 
  * Review the documentation of the modules and work done.
  
## Works already done
* Implemented floor_divide on Object type (#455).

**Comment by freakboy3742** [comment]
This seems extremely optimistic as a timeline. You're proposing to implement all remaining data types, 4 builtin modules, *and* tackle optimization. While I appreciate the enthusiasm, it doesn't seem realistic at all. 

But more importantly - this proposal gives me no reason to believe your estimates. You say it will take 3 weeks to finish all the data types. I've been working on VOC for 18 months - admittedly, in a part time capacity, but still - I've spent more than 3 working weeks on it in total, and it feels like a lot more than 3 weeks work to me - and I'm an expert on the subject matter. 

The optimisation task (#75) *definitely* feels like more than week of work - unless you can see an optimisation path that I can't see. In which case, I need details to know what you've got in mind.

I think you need to spend a bit more time working on this proposal and backing up your extremely optimistic timelines. If it turns out you really are this productive, and you are able to do this much work - that's fantastic - but remember:

1. We're looking for quality, not quantity

2. The onus is on you to convince us that you can meet this schedule.

**Comment by AdilsonTorres** [comment]
Yes, I was optimistic. That's because I considered some factors:
1. About the builtin data types, I know this takes time to do, but I'm considering the work already done, which means that from what I've seen a lot of things has been done, so I don't think that there is so much thing to do, and I also considered what is currently being worked on (#36 and others issues). Even so I underestimated what is still missing.

2. Still about builtin data types, I realized that many implementations serve multiple data types, so if I solve one, it can solve several.

3. About optimization, because I'll already be working on data types, I'll be more familiar with the way of doing what makes more easier to find possible solutions for optimization. Even so I must admit that 1/2 weeks should not be enough.

4. About the stdlibs, I considered a path to follow, ie my final goal would be if possible to finalize re stdlib, but for this it depends on some implementations of other modules (enum, which in turn depends on functools), and if I could finish this, I would start the argparse stdlib. That is, re stdlib would be my priority, which leads to implement functools and enum (at least possible to guarantee all functionality for the module re), and if it takes time to start argparse.

5. And in general I planned to work on more than one topic, that is, implement functions on builtin data types, implement optimizations related and implement a stdlib, so that I can get the most out of the project and GSoC.

So, considering I did a very optimistic planning, I think I can adjust so that in the related weeks to builtin types reduce the numbers of builtin (depending on what is missing). In the optimization part try to make those related to those that are already done. And to finish doing the implementation of re module and parts of previous modules (enum, functools) that may be necessary, leaving argpase module as something extra. What do you think about this, @freakboy3742?

**Comment by freakboy3742** [comment]
Unfortunately, this proposal wasn't accepted.
