### ISSUE TITLE
GSoC 2017 proposal: Implementation of builtin types Int, Float, Complex and Str 

### ISSUE THREAD

**Issue by Saurabh--Kumar** [pybee/voc#483]
Looking forward to feedback:

	 	 	
**Proposal for VOC Project:**

**Personal Information:**
Name - Saurabh Kumar
University – BITS Pilani, Pilani, India
Major – Computer Science and Physics (Final Year undergraduate student)
email – bhardwajsaurabh10@gmail.com
Github - https://github.com/Saurabh--Kumar 

**Task:**
I would be completing all the not implemented methods of types Int, Float, Complex and Str, along with their tests. If time permits, I would like to implement math, cmath and fractions modules also (in decreasing order of preference).

**Success:**
Complete implementation of all the non implemented methods of Int, Float, Complex and Str types. It would be nice to implement some of the optional modules also (math, cmath and fractions).

**Experience with Open source:**
I am new to open source but I have got my following PRs merged in VOC project in last few days
1. https://github.com/pybee/voc/pull/408
2. https://github.com/pybee/voc/pull/445
3. https://github.com/pybee/voc/pull/448
I’ll be submitting more PRs shortly.

**Design Specification:**
Pretty much all the methods of types Int, Float and Complex are easy to implement except the \_\_format\_\_() method which I find challenging. Other than that, in Str, I find maketrans(), translate(), isprintable(), isnumeric(), format(), format_map(), encode(), casefold() and \_\_rmod\_\_() challenging. maketrans() and translate() are related and so are format() and format_map(). So understanding one of them will definitely help in understanding the other. These challenging methods require discussion and research so I think i’ll be able to implement 2 or 3 challenging methods in a week, however, in timeline I have taken one challenging method per week along with some easy methods to keep the momentum going. In timeline I have also included the part about the methods which I find challenging.

*There are some PRs pending for some of the string methods currently unimplemented, I’ll remove those methods once the PRs are approved.
*I didn’t find any documentation for byvalue() method for Complex type online. What does this method do? I have not included this method in my time estimate.
*Optional modules are not included in the timeline estimate.
* The challenge and the way I am planning to tackle that challenge for the difficult methods is written in the timeline itself.

**Timeline:**

**Community bonding period:**

- Will be discussing my doubts relevant to challenging methods with mentors.
- Will be doing research on handling encoding in java for encode() method and format(), format_map() methods (basically I'll try some simple examples using the specification language) 
- Will be submitting more PRs.

**May, 30 – June,6 (Week 1):**

- Will implement following Str functions: isidentifier(), replace(), rsplit(), splitlines()
- Will implement following Float functions: \_\_pow\_\_(), complete implementation of round()

**June,6 – June,13 (Week 2):**

- Will implement the following Str functions: maketrans(), translate()
- Challenge: Dictionary argument may be challenging. I am planning to use java Maps to create a mapping between characters to be replaced and characters being replaced.

	
**June,13 – June,20 (Week 3):**

- Will Implement following Str functions: rpartitrion(), \_\_rmul\_\_(), \_\_dir\_\_()
- Will implement following Complex methods: \_\_bool\_\_(), \_\_dir\_\_(), \_\_float\_\_()

**June,20 – June,27(Week 4):**

- Will implement r methods for Int
- Will implement r methods for Complex.

**1st evaluation**

**June,27 – July,4 (Week 5):**

- Will implement following Str methods: isnumeric(), isprintable()
- isprintable() can be implemented with help of [this](http://stackoverflow.com/questions/220547/printable-char-in-java). With some research, I found the [list](url) of numeric unicodes. This list can be used for implementing isnumeric().

**July,4 – July,18 (Week 6 - week 7):**

- Will implement following Str methods: format(), format_map()
- Challenge: There are many formatting options moreover the[ format specification](https://docs.python.org/3.4/library/string.html#formatstrings) is a mini language in itself. Since both methods look related. I have allotted 2 weeks for these.

**July,18 – July,25 (Week 8):**

- Will implement \_\_dir\_\_() and \_\_format\_\_() method for all numeric types. Int, Float and Complex.

**2nd Evaluation**

**July,25 – August,1 (Week 9 week - 10):**

- Will implement encode() method for Str.
- Challenge: There are several types of encodings available. [JAVA 7](http://docs.oracle.com/javase/7/docs/technotes/guides/intl/encoding.doc.html) supports all the encodings supported by [Python 3.4](https://docs.python.org/3.4/library/codecs.html#standard-encodings) . Python stores characters as code points which can be converted from one encoding to other. I plan to use [java.nio.charset](https://docs.oracle.com/javase/7/docs/api/java/nio/charset/package-summary.html#package_description) package to convert between  different encodings. 
- Will try to complete casefold() method.
- Challenge: Casefolding algorithm. The current implementation of casefold() function is not quite correct. After doing some research, I found the [unicode casefolding data.](http://unicode.org/Public/UNIDATA/CaseFolding.txt). It covers all the boundary cases. I plan to use this for casefolding implementation.

**August,8 – August,15 (Week 11):**

- Will complete casefold() method if remaining.
- Will implement remaining Float methods.

**August,15 – August,22 (Week 12):**

- Will implement \_\_rmod\_\_() for Str type.

**August,22 – August,29:**
**Final submission**

**Comment by freakboy3742** [comment]
Thanks for submitting this proposal. It's a good start.

My biggest concern is the "backlog" and "as many as possible" allocations in your schedule. The entire purpose of the scheduling process is to remove risk. If you need to add "backlog" allowances to your schedule, that's an indication that more elaboration is required.

Your handling of "challenge" items is better - you've started to identify helper libraries and details like that - but more detail is still required. This isn't an area where we're looking for vague plans - we want specifics. Which parts of the standard library can you use? Where does Java deviate from Python in API? 

Your schedule also shouldn't include allocations for "discussion" - it goes without saying that you'll be discussing plans with both your mentor, and the wider community. But more importantly, if there are issues where the discussion is significant enough that it warrants inclusion on your schedule, that discussion should be happening *now*, so we can guide your time estimates.

**Comment by Saurabh--Kumar** [comment]
@freakboy3742 I have made changes to the proposal as per your suggestions. Please go through this modified proposal. waiting for your feedback. Thanks.

**Comment by freakboy3742** [comment]
Unfortunately, this proposal wasn't accepted.
