### ISSUE TITLE
GSoC Proposal: Complete implementation of Str, Dict, Int and Float types and Complete implementation of math and cmath modules.

### ISSUE THREAD

**Issue by sohit-nayak** [pybee/voc#489]
# Project Details :
## Introduction
-----

VOC still lacks the implementation of some important functions in the Str and Dict builtins and also most of the `__r*__` methods of Int (15) and Float (12). I would be fixing all of the `NotImplementedError` of these four datatypes. And as far as module implementation is concerned, I have targeted `cmath` (complete) and `math` (complete) modules.
Some of the functions require a mention and the way they are to be tackled are also specified. This project would primarily comprise of three components which I describe below:
1. **Str Methods** - As of now there are 18 methods to implement, out of which 3 are fairly **complex**. These are `casefold()`, `format()` and `format_map()`. Then we have `isidentifier()`, `isnumeric()`, `isprintable()`, `maketrans()` and `replace()` which can be put in the **medium** category. Time required for a complex function would be roughly 3 days, while a medium difficulty should not take more than 2 days to implement. Here are some insights on the tough functions on how I am planning to tackle them: 
    * replace() - I am planning to use the java.lang.split() function and then concantenate the list of strings with the desired string.
    * rpartition() - I have already submitted a PR #472 regarding this function.
    * casefold() - I did some research on casefolding operations in java, and though wasnt able to find any particular API, have submitted a PR #480 which solves the problem. More information is provided in the schedule.
    * format() - Handling this method will be a bit tricky, due to all the positional formatting offered by `format()` as mentioned [here](https://docs.python.org/2/library/string.html#format-examples). Apart from this, varargs and kwargs will also come into play. Complete breakdown of format() is provided in the schedule. 
    * format_map() - Implementing this method wont be too difficult after `format()` since both are quite similar in nature, except that the mapping used in format_map is used directly rather than copying in a Dict.

    Apart from these functions the rest are either simple and should'nt pose any problems.
2. **Dict methods** - There are 3 unimplemented methods in the Dict class as of now. These are `keys()`, `update()`, and `values()`. Of these three, update() would be fairly simple to implement.
    * keys() and values() - java.util.HashMap.keySet() method can be used to directly extract keys of the HashMap and values() can also be extracted by java.util.HashMap.values(). The only problem is that these dont not return a simple List rather return [view objects](https://docs.python.org/3/library/stdtypes.html?highlight=dict#dict.keys).
    
    While implementing these types I will be also working on the __r*\_\_ methods of Int and Float. This should be pretty easy since they are just the reversal of the left-side operators already implemented.
3. `math` and `cmath` **module** - These modules are pretty basic mathematical manipulations which would be mostly easy to implement. I have categorised the functions as easy, medium and hard. The math module contains about 44 methods (and 5 constants) out of which the Logarithmic , Angular Conversions and Trignometric functions would be fairly easy to implement using [java.lang.Math](https://docs.oracle.com/javase/7/docs/api/java/lang/Math.html).Though there are no direct implementations of some functions like `frexp()`, `gcd()`, `isclose()`, `factorial()` and `log(x[,base])`, implementing them would call for some simple mathematical manipulations. There are 7 such functions and these fall in the 'medium' category. The 'hard' category will include `erf()`, `erfc()`. After some digging I came across [this](http://introcs.cs.princeton.edu/java/21function/ErrorFunction.java.html) which might be of help while implementation. These are complex mathematical operations on probability distribution. Since I am already familiar with Probability Distributions (have done a course on Probability and Stochastic Processes this semester), I will just have to convert logic into code. 
The cmath module contains 21 methods (and 2 constants). It includes Conversion, Trignometric, Logarithmic and Hyperbolic functions which should not give me any trouble. Hence, this should also not take much effort and time to implement.
**Note**: Though implementing these modules would'nt be so difficult(mostly) still it has to be very meticulous. The implementation will raise ValueError for invalid operations like sqrt(-1.0) or log(0.0), and OverflowError for results that overflow (for example, exp(1000.0)) and hence I will have to make sure everthing is handled properly.

# Schedule of Deliverables
-------------------
**My Summer vacations start from the 1st of May**, and I would be able to dedicate 6-8 hours of work daily. After 17th of July, I might be forced to cut down to 5-6 hours due to the start of my 5th semester. 
I have a **fairly good knowledge about Git/Github** and have been using for a good amount of time. Though I am familiar with the codebase, I still need to get along with the OpCode handling and `ast.py`, which would be in the early part of my schedule.
On the final day of every week, I intend to **work on the documentation** adding any significant changes made. I **won't be having any other commitments this summer**. I also intend to start a **basic blog tracking my GSoC progress**, since it would become very simple and organized to view the changes and progress made. 
## Timeline : 
-----
Throughout the coding period, emphasis will be laid on well documented and tested code. This is achieved by verbose commit messages, comments and by following a test-driven development style.
#### Community Bonding Period ( May 5th - 30th ) : 
* Spend time interacting with the community members and learn more about VOC, specifically handling of python bytecode.
* Research more on `casefold()`, study syntax of the positional formatting offererd by `str.format()`.
* Study the definition and distinction between `nan` and `inf`. Also study the operations involving them.
* This period can also be used to furthur refine, discuss and plan the components of proposal which are not very clear.
#### Week 1 ( May 31st - June 2nd ):
* Since this would rather be a short week, I will start implementing `splitlines()` and `isnumeric()` methods along with tests.
* I have already studied the documentation for these methods and these methods would not pose any problems.
* Finish implementation on the above methods and complete documentation.

#### Week 2 ( June 5th - 9th ):
* I plan to implement a difficult method along with some easy ones. Hence, I will start work on `casefold()`. Though PR#480 ( somewhat ) solves this problem and [this](https://docs.atlassian.com/jira/7.1.6/com/atlassian/jira/util/CaseFolding.html) also backs the logic used, but it's not 100% correct ( for example the Turkish 'I' ).
* Apart from casefold() I will be implementing `isprintable()`. Characters that occupy printing space on the screen are known as printable characters. For example: letters and symbols, digits, punctuation, whitespace. 
* Implement `__radd__` and `__rsub__` of the Int type.
* Complete documentation and tests of all added methods.

####  Week 3 ( June 12th - June 16th ):
* Implementation of `encode()` method - Since Python 3.0, strings are stored as Unicode, i.e. each character in the string is represented by a code point. So, each string is just a sequence of Unicode code points. Using encode() method, one can convert unicoded strings into any [encodings supported by Python](https://docs.python.org/3/library/codecs.html#standard-encodings). As it happens, classes in the `java.nio.charset` package can convert between Unicode and a number of [other character encodings](http://docs.oracle.com/javase/7/docs/technotes/guides/intl/encoding.doc.html). And after cross-checking between the two, I found out that the java class covererd all the encodings supported by python. The classes to be used are `java.nio.charset.Charset` which are also [available](https://developer.android.com/reference/java/nio/charset/package-summary.html) for android.
* Implementation of `isidentifier()` - All the qualification rules for an identifier are to be checked.
* If time permits, I will implement `__rmul__()` and `__rtruediv__()` of Int type.
* Test cases are to be written along with documentation.

#### Week 4 (June 19th - June 23rd):
* Read the documentation and implement `replace()`, `rpartition()` (PR submitted), `rsplit()` methods of String type along with the tests.
* Partial implementation of `format()` - There are a number of syntax implementation of format() method. In this week I intend to implement formatters with multiple placeholders and reordering formatters with positional and keyword arguments. This will require heavy use of regular expressions.
* Implement __format__() of string and Int type.

 #### Mid-Term Evaluations Week(June 26th - June 30th ):
*  Complete implementation of `format()` - Implementing formatters with specifiers would be a bit tricky and requires research and some thinking. The conversion type refers to the the single-character type code that Python uses. The codes that we’ll be using here are s for string, d to display decimal integers (10-base), and f which we’ll use to display floats with decimal places. Finally, padding variable substitutions and keyword arguments are to be implemented.
* Start the implementation of `format_map()`.
* Write tests and documentation for the methods.
* Complete implementation of ` __format__()` of float.

#### Week 6 ( July 3rd - July 7th ):
* Complete `format_map()` implementation.
* Start work on the final pair of methods, `maketrans()` and `translate()` - maketrans() returns a Dictionary which maps the ord of the old and new characters, which is used by the translate() method for replacing the characters.
* Implement `__rfloordiv__()`, `__rmod__()` of the Int type.
#### Week 7 (July 10th - July 14th):
* Start implementing methods of Dict type, i.e `update()` and `keys()`.
* `update()` - The update() method updates the dictionary (sorted)  with the elements from the another dictionary object or from an iterable of key/value pairs. Apart from this, a dict can also be updated using kwargs.
* Wrap up all the `__r*__` methods of Int (7 remaining).
#### Week 8 (July 17th - July 21st):
* Complete implementation of `values()` which would be fairly similar to that of keys(), hence should'nt consume much time.
* Start the implementaion of the `math` module with some easy functions (the ones having direct java APIs) `ceil()`, `copysign()`, `fabs()` and `floor()`.

#### Week 9 (July 24th - July 28th):
* Continue with `math` module . Implement the `fmod()`, `frexp()`, `fsum()`, `exp()`, `ldexp()` and `expml()`.
    * `fmod()` - java modulo operator works with the same precision of digits with float as that of fmod().
    *  `frexp()` - Since the exponent is an integer and mantissa is less than 1, a simple loop check would do the trick.
    * `ldexp()` - inverse of frexp(). 
* Implement all trignometrical functions (8 in total) - All of these methods have implementations in java.
* Start implementation of Float type methods. Implement `__pow__()` (with modulo) and `__round__()` with(n digits).

#### Week 10 (July 31st - August 4th):
* Implement all logarithmic functions (6 in total) and angular conversion functions (2) - While there is no implementation of custom bases for log in java, it only requires a simple formula to convert to the ratio of natural logarithms.
* Implement `factorial()` using a fast algorithm as mentioned [here](http://www.luschny.de/math/factorial/FastFactorialFunctions.htm).
* Implement `isclose()`and `gcd()` - The [java.math.BigInteger.gcd()](https://www.tutorialspoint.com/java/math/biginteger_gcd.htm) can be used for `gcd()` implementation.
* Complete implementaion of the remaining r methods of Float type.

#### Week 11 (August 7th - August 11th):
* Implement `erf()`, `erfc()`, `gamma()`, and `lgamma()` - though there is no API as such, I found some material on [gamma](http://introcs.cs.princeton.edu/java/91float/Gamma.java.html) and [erf](http://introcs.cs.princeton.edu/java/21function/ErrorFunction.java.html) which could of much help.
* Complete implementation of the math module with remaining methods, `isfinite()`, `isinf()`, `isnan()` , `modf()` and `trunc()`.
* Start implementation of `cmath` module with easy and similar functions - Exponential, Logarithmic and Hyperbolic functions. While there is no java API for complex numbers operations, these are just one-line formulas like some mentioned [here](https://en.wikipedia.org/wiki/Complex_logarithm).

#### Week 12 (August 14th - August 18th):
* Implement Transformation functions `phase()`, `polar()`, `rect()`.
* Complete cmath with `isinfinite()`, `isinf()` and `isnan()`.
* Add all constants for both modules.

#### Final Week:
* The final week will be for doing brush-ups on all the code implemented. Implement remaining r methods of Float and Int type. Make sure everything is well documented and tested.

## Involvements with VOC
------
I have already worked on some methods of Str type and am pretty familiar with the python signatures for java-defined methods. PR's submitted by me:
1. PR #385 (merged) - Implements `ljust()` method of string type.
2. PR #439 (merged) - Implements `rstrip()` and `lstrip()`.
3. PR #472 (open) - Implements `rpartition()`. There were some missing test-cases which are included and ready for review.
4. PR #480 (open) - Implements `casefold()`.

**Comment by sohit-nayak** [comment]
@freakboy3742 Hi, is there anything I must consider adding or changing here? I know there are some minor changes to be done (casefold, etc.), but is there any overall flaw ? (This is my first proposal) Thanks! :smile:

**Comment by freakboy3742** [comment]
Hi Sohit - thanks for the proposal, and apologies for the delay in giving feedback. On the whole, this looks reasonably good; you've got some good detail on approaches and libraries you're going to use. Some comments:

* References like "finishing last week's work if needed" undermine your scheduling. The purpose of the scheduling process isn't to take a body of work and divide it into 12 parts; it's to work forward from individual parts and come up with an overall estimate. If your timeline has "contingency" time in it, this is evidence that more elaboration is required. You should be able to state with relative confidence how long each block of work will take.

* references to `java.nio` need to confirm that those libraries are available on Android as well.

* Are you sure cmath will be as simple as you claim? Complex math can be *very* complicated - Does Java provide the necessary tools to support this?

**Comment by sohit-nayak** [comment]
@freakboy3742 thanks for the review! I will consider all the comments aforementioned while preparing the next edit. 
* Will remove any contingency time to make the schedule more solid.
* Will research more on `java.nio` and mention about it.
* Will be more elaborate on each function of `cmath` in the schedule.
Thanks! :smile:

**Comment by freakboy3742** [comment]
Unfortunately, this proposal wasn't accepted.
