### ISSUE TITLE
GSoC 2017 proposal: Implementation of Int, Float and Str

### ISSUE THREAD

**Issue by TheGamer007** [pybee/voc#491]
### Personal Details
**Name:** C Shri Akhil  
**Nationality:** Indian  
**Time Zone:** GMT + 05:30  
**Email:** cshriakhil@yahoo.co.in  
**Gitter Handle:** @TheGamer007  
**GitHub Username:** @TheGamer007  
**College:** BITS Pilani, Hyderabad Campus  
**Undergraduate Degree:** 2nd year student in Electrical and Electronics Engineering

## Success Conditions
100% implementation of all the unimplemented methods in `int` and `float`, and 80% implementation of `str`. The test cases listed in the proposal should also be supported by respective binary operators.

## Design Specification

Following is how I plan to go about the implementation. While I have listed the methods module-wise, methods common to or similar between them will likely be done together.   

### `int` details

Methods remaining :

* `Int()` : Needs to handle a base being passed. Java should have sufficient methods to achieve this. `parseInt()` being one of the methods that strikes at first glance.

* `__format__()` : This is called when the `format()` built-in method is used. Exact details need to be figured out, but given the partially implemented code in `str` it shouldn't take too much time.

* `__dir__()` : This is supposed to return a list of attributes associated with the type. It is called whenever the built-in `dir()` method is used on an `int`.

* `__mul__()` : According to [this answer](http://stackoverflow.com/a/5182501) on StackOverflow, `int` shouldn't handle string multiplication itself, but rather call `rmul` for the string object. This is a very minor issue in any case, as the output isn't being affected.

* There are 13 `r`operator methods which should be very simple to implement. These are, however, **not** simply reversing the order of invocation from what I can see (I noticed this perception on other proposals and their comments). These methods are called when the first operand cannot handle the operation, meaning the code here is expected to handle it. Simply reversing would not help since it isn't implemented there either.

* (Binary) `test_modulo_complex`, `test_power_complex` and `test_true_divide_complex`

### `float` details

Methods remaining:

* `__format__()` : Implementing the `int` one first might help providing a base on which minor changes will suffice.

* `__dir__()`

* `__mul__()` : According to the `test_float.py` file, multiplication is yet to be implemented for `bytearray`, `bytes`, `class`, `complex`, `frozenset`, `NotImplemented` and `range`. 7 in total. ~~Judging by the fact that they haven't been solved already, I am expecting there to be some twist that either requires some mechanical work or finding a proper Java equivalent. I will update the timeline with a more accurate estimate after taking a proper glance, before the final submission.~~ These are actually quite simple and might have been left only due to their not being used too often.

* (Binary) `test_modulo_complex`, `test_subtract_complex`, `test_power_complex` and `test_true_divide_complex`

* (Binary) `test_power_float`

* `__pow__() with modulo` : According to the documentation, the result is the same as `pow(x,y) % z` but it is computed more efficiently. Unsure of how to make it more efficient. There is a `modpow()` method in the Java data type `BigInteger`, but this type is known to be generally less efficient due to variable precision. Insights can definitely be gained from the source code, at the very least.

* `r`operator methods: 8 methods in all. Implementing corresponding `int` ones first will make an already simple process faster.

* `__round__()` with ndigits : The way Java handles rounding, combined with [certain limitations in the Python floating arithmetic](https://docs.python.org/3.4/tutorial/floatingpoint.html#tut-fp-issues) might require extra cases to be considered. From a cursory glance, `DecimalFormat` class along with the proper flags can emulate most of the behaviour required.

### `Str` details

The foremost reason I aimed at only 75% rather than a complete implementation is because of certain Complex functions that seem beyond my scope, at least in their entirety. Of course, if I stumble upon an easier solution or if time permits I would love to implement those as well.

#### Simple Methods

These are methods whose implementation is fairly straightforward and achievable with little or no effort.

* `__dir__()`

* `__rmul__()`
* `__rmod__()`: Will need to check cases where these are being called and implement accordingly.

* `replace()`: Java built-in function with minor tweaks should suffice.

* `rpartition()`: From what I can see, the only change from `partition()` is in the tuple returned. While `partition` returns `(sep,'','')` on a missing `sep`, `rpartition` returns `('','',sep)`.

* `rsplit()`: Shouldn't be much work, especially since `split()` is already implemented.

* `splitlines()`: While it may essentially seem similar to calling `split('\n')`, it requires handling of other line break characters as well as the slight change in returned values. Documentation of the method is detailed, so no foreseeable complications.

#### Semi-Complex Methods

* `Str() with encoding`: Java already having a `String` constructor that allows the specification of encoding makes this seem like a simple method. However, there seem to be some encoding formats supported by Python and not by Java under that. In such cases, conversion to a Java `bytearray`, then encoding, and finally reconversion seems to be an option. This method is in Semi-Complex simply as a worst-case and will mostly end up a lesser amount of time.

* `isidentifier()`: Documentation provides enough detail, but the number of cases seem to be large. [This](https://docs.oracle.com/javase/7/docs/api/javax/lang/model/SourceVersion.html#isIdentifier(java.lang.CharSequence)) seems to be a native Java method that does a similar operation, but I'm reasonably sure there will be differences that need to be manually checked.

* `isnumeric()`: There is a possible usage of the `NumberFormat` class. The Apache Commons library seems to provide an almost exact implementation at first glance. If using a library is fine, then this should take hardly any time.

* `isprintable()`: The `Character.isISOControl(int)` method seems to be a good place to start. The documentation provides an almost exact list of which characters need to be passed, so handling the ones that differ shouldn't be an issue.

* `encode()`: Java does not support directly encoding Strings and requires conversion to `bytearray`. Many cases of this to and fro conversion result in accidental loss of character data. A rudimentary conversion to Java supported encodings should however be directly implementable.

*Note: The reason for putting the following three formatting methods in Semi-Complex rather than under Complex is because I implemented part of the `mod` operator i.e. the Old String Formatting. The RegEx should be able to support this with a decent amount of changes. If there is too much divergence, then lesser time will be left to be allotted to the optional Complex methods.*

* `format()`: This is the method invoked in cases of `str.format(args)` being called. From what I could gather, this has some additional/slightly different functionality as compared to the newer `format(str,args)` built-in.

* `__format__()`: The complexity of this depends on the amount of differences between this and the above. Put under Semi-Complex heading as a worst-case.

* `format_map()`: This method takes a mappable object as a parameter and uses that for doing the same operations as `format`. The reason for a separate method is because `format` copies the object into a `Dict` and this results in a loss of custom handling by a subclass. Once `format` is implemented, this should follow soon.

#### Complex Methods (Not part of deliverables)

* `casefold()`: This is currently implemented as `str.toUpper().toLower()`, which is a very crude approach with multiple fail cases. Some quick searches indicate that [this](http://icu-project.org/apiref/icu4j/com/ibm/icu/lang/UCharacter.html#foldCase-java.lang.String-boolean-) library might help.

* `maketrans()`: A function that returns a translation table usable with the `translate` method. There seems to be no library or Java method that pops out as a simple solution.

* `translate()`: A function that translates a given string based on the mapping passed as a table. Again, no clear Java alternatives in sight.

#### Community Bonding Period (5 May to 2 June)

* Semester-end  evaluations till 15 May
* Maintain regular contact with community on Gitter
* Look for better solutions to the tougher methods in `Str`

#### Week 01 : 05 June to 09 June

* Implement `int` constructor with base
* Implement `__format__` for `int`

#### Week 02 : 12 June to 16 June

* Implement `__format__` for `float`
* Implement `pow` for `float`

#### Week 03 : 19 June to 23 June

* Implement `format`, `format_map` in `str`

#### Week 04 : 26 June to 30 June

* (Continued) Implement `format`, `format_map` in `str`
* Make `test_modulo_complex`, `test_power_complex` and `test_true_divide_complex` pass for `int`

#### Week 05 : 03 July to 07 July

* Implement `isnumeric`, `isprintable` and `__format__` in `str`
* Implement `rpartition`, `rsplit` and `isidentifier` in `str`

#### Week 06 : 10 July to 14 July

* Finish Practice School
* Implement the `r`operator methods for `float`, `int` and `str`

#### Week 07 : 17 July to 21 July

* Implement `replace` and `splitlines` in `str`
* Implement `__round__` for `float`

#### Week 08 : 24 July to 28 July

* Implement `encode`

#### Week 09 : 31 July to 04 August

* Start the new semester
* Implement `__mul__` for `float` ( with 7 types)

#### Week 10 : 07 August to 11 August

* Implement `__dir__` for `float`, `int` and `str`

#### Week 11+ : 14 July to 21 August

* Make `test_modulo_complex`, `test_subtract_complex`, `test_power_complex` and `test_true_divide_complex` pass for `float`
* Make `test_modulo_float` pass for `float`

## Contributions

Currently working on pybee/voc#469 that deals with the Old String Formatting using `%` operator. It is a work in progress and has not been merged yet.

#### Programming Background
I've been dabbling in Java for over 4 years, ever since I took it up as a subject in high school. I picked up Python over a year ago, but gained a decent amount of experience by developing a few projects. I also develop Android apps.

Given this background, I was quite interested when I came across VOC which was essentially bridging the gap between the two. This also gives me a great opportunity to learn more about the internals of Python and Java, something I have not explored in detail yet.

I am adept at using version control, and have a few open source repositories that you might check out if interested. Especially [MangaHub](https://github.com/TheGamer007/mangahub) which was developed in a style similar to GSoC, but over the winter.

#### Other Interests

Apart from programming, I like to spend my free time reading novels, watching Anime/Manga and writing/editing articles.

#### Commitments

My current semester ends on May 15th and the next one begins from 1st August. There will be negligible workload from classes since the coursework is light during the initial weeks.

At the end of 2nd year, the institution sends all students to a mandatory internship called **Practice School** that lasts over the summer (23 May to 15 July). However, the primary aim of this internship is to serve as exposure and let us observe how work is done in industries, so it would not take up much of my day. The timeline has been made accordingly and it will not affect my ability to contribute to this project in a significant way.

Apart from this, I have no other obligations. I am certain I will be able to do justice to VOC, since I am accustomed to juggling deadlines and coursework on a regular basis.

**Comment by freakboy3742** [comment]
Thanks for submitting this proposal. This is a solid effort - you've done plenty of research, and this proposal shows the result of that.

The only significant comment I'd make is that the existence of "buffer" time in your proposal is a bit of a red flag. The purpose of planning is to work out how long a body of work will take, and eliminate risk; you should be able to state your timeline with sufficient confidence that there isn't a need for buffer time. If you're not confident in your timeline - then more elaboration is required.

**Comment by TheGamer007** [comment]
@freakboy3742 Thanks for the feedback. I'll make the necessary edits to the timeline. Like I mentioned, I had to reevaluate the time required for certain other methods in any case. If they seem to be falling short of 12 weeks, I'll take up some more tests.

**Comment by TheGamer007** [comment]
@freakboy3742 Edits made based on your suggestions. To summarize what's new:
* `__mul__` for `float` seems to be quite simple, and hence will not require as much time.
* Based on my current problems with the `%` operator, the formatting methods in `str` might require slightly longer due to presentation differences between Java and Python. Hence, some extra time assigned there.
* The tests in `int` taken up as part of proposal rather than tasks to be done if buffer isn't needed.

**Comment by freakboy3742** [comment]
Unfortunately, this proposal wasn't accepted.
