### ISSUE TITLE
GsoC Proposal: Implementation of "os.path" and "random" modules

### ISSUE THREAD

**Issue by SouravJohar** [pybee/voc#500]
## Implementation of ‘os.path’ and ‘random’ modules
29.03.2017
─
**About me:**
I am Sourav Johar, a 2nd year Computer Science undergraduate from Amrita Vishwa Vidyapeetham, India. I’m a Python programmer and I’ve worked quite a lot with Java also.
I would love to contribute to VOC during my summer. I’ve always had a knack for programming, and thus I enjoy my work and I’m very diligent towards it. I also know git and github and have been using for about two years now.

### **Overview**

I would like to implement the os.path standard library and partially implement the random library. Pathname manipulations is often a necessity in any kind project, big or small. I’d like to contribute by implementing the 29 functions of the `os.path` sub module.And as paths are platform dependent, the class will be made compatible for all platforms.
 Generating random values and permutations is also a key part of many projects. I will implement the most commonly used functions of the `random` module - `randrange`, `randint`, `choice`  and `shuffle`.

### **Implementation**

A lot of the functions of the os.path module have a very similar Java counterpart function too. I will be using the functions of `Java.io.File` class to replicate these functions. 

The functions of os.path such as `isabs()`, `isfile()`, `isdir()` etc., come under this category. These functions will be relatively easy to implement. A few other functions in this category are different variations of almost the same thing, `splitdrive()`, `splittext()` etc. and I will use Java’s `split()` method to tackle them.
Hence, I’ve categorized such functions as easy.

Some functions of the os.path module such as `exists()`, `lexists()`, although not that hard to implement, might have certain extra cases to care of, like Symbolic Links. I plan to categorize these under semi-complex. Method `relpath()` also falls in this category.

Methods such as `expanduser()`, `expandvars()` and `join()` require more research than the others, and they do not have an underlying Java function, making things a bit difficult. Moreover,`expanduser()` relies on Python’s standard library module `pwd`, which has not been implemented yet. Therefore, I will have to solve this with a workaround and later when the `pwd` module is written, necessary changes will be made.
All these functions will be designed for both Unix and Windows as they follow a different format of paths.

Methods like `getmtime()`, `getctime(), `getatime()` might also be tricky, since its system time dependent, and different platforms have different metrics to calculate time.
(Unix uses time elapsed since “epoch”,  Jan 1, 1970 ) 

For the `random` module, I will be implementing `randint()`, `randrange()`, `choice()`, and `shuffle()`. These functions also have helper Java methods (`Java.util.Random`). I will be using these methods with small variations and basic math to achieve this. These functions although not hard to implement, might require some time to match the exact way random module’s function work.

### **Timeline**

**Community Bonding: May 4 – 30**

- Involvement with mentors and colleagues on github and gitter
- Research about how different platforms calculate time
- Investigate where the modules should go on pybee/voc and how to implement them
- Learning the math behind `choice()` with weights.

**Week 1: May 30 – June 2**

- Tackling the easy ones first -  `abspath()`, `getsize()`, `isabs()`, `isfile()`, `isdir()`, `realpath()`
- These functions have direct methods from Java.io.File

**Week 2: June 5 – 9**

- Implementing `basename()`, `split()`, `splitdrive()`, `splittext()`
- Implementing `commonpath()`, `commonprefix()`, and `samefile()`
- These functions will use Java’s split method majorly, and basic string manipulation.

**Week 3: June 12 – 16**

- Work on `expanduser()` and `expandvars()`

**Week 4: June 19 – 23**

-  Continue any left off work from previous week, if any.
-  Implement `join()`

**Week 5: June 26 – 30**

- Tackle time issues with different platforms
- Implement `getmtime()`

**Week 6: July 3 – 7**

- Implement `getatime()` and `getctime()`

**Week 7: July 10 – 14**

- Implement `islink()` and `ismount()`
**Week 8: July 17 – 21**

- Finish any left off work from previous week, if any
- Implement `samestat()`
- This uses the underlying principle of samefile(), should be fairly simple to do

**Week 9: July 24 – 28**

- Implement `exists()` and `lexists()`
- Start implementation of `relpath()`

**Week 10: July 31 – Aug 4**

- Finish implementation of `relpath()`
- Implement `normpath()` and `normcase()`

**Week 11: Aug 7 – 11**

- Implement `sameopenfile()`
- Final checks on `os.path` module
- By the end of this week, `os.path` should have been implemented fully

**Week 12: Aug 14 – 18**

- Start work on the `random` module
- Implement `randint()` and `randrange()`

**Week 13: Aug 21 – 29**

- Implement `shuffle()` and `choice()`
- Implement the overloaded method (with weights) of `choice()`
- Final checks on `random` module 
- Submission of final work for evaluation

**Previous contributions towards VOC:**

Implemented the splitlines() function
[PR #478 (open)](https://github.com/pybee/voc/pull/478)

Apart from this, I have understood the codebase of VOC and have attained a good knowledge of how things work in a big open source organization. I would be extremely fortunate to be selected in this prestigious program and would be excited to work for this organization.

**I completely understand that this is a genuine commitment. I will devote 30+ hours per week for this and I would count my work as a success if I am able to deliver everything that I’ve proposed to.**

**Comment by freakboy3742** [comment]
Thanks for submitting this proposal. Some feedback for you:

* Have you investigated the prospects for file operations on Android? It's OK if you're going to consider it out of scope for your project, but you will need to reference it *somehow*.

* References like "finishing last week's work" undermine your scheduling. The purpose of the scheduling process isn't to take a body of work and divide it into 12 parts; it's to work forward from individual parts and come up with an overall estimate. If your timeline has "contingency" time in it, this is evidence that more elaboration is required. You should be able to state with relative confidence how long each block of work will take.

* You've spoken about the methods in the time module you're going to implement, but made no mention of any data types. That seems like a big omission.

**Comment by SouravJohar** [comment]
There are only 3 functions in `os.path` which involve time. And the value returned by these numbers is just a float data type, not a special datetime object. So, I've to only work with floats. Am i missing anything?

**Comment by freakboy3742** [comment]
Unfortunately, this proposal wasn't accepted.
