### ISSUE TITLE
GSoC VOC Project: Implementation of int, float and Complex for Python and JVM interlink

### ISSUE THREAD

**Issue by aviplaw** [pybee/voc#507]
Google Summer of Code 2017 Proposal 
The IDEs of Python. Tools for cross-platform Python application development.

“Python on the JVM: VOC Project”

 
= Personal Details = 
Name: Anurag Viplaw 
University: University of Petroleum and Energy Studies 
Email: viplaw.anurag14@stu.upes.ac.in 
Github: aviplaw 
Linkedin: linkedin.com/in/anurag-viplaw-88185a113/
Skype: +91 7060212580, +919006291010 
Time-zone: UTC+5:30 

Success Conditions
100% implementation of all the unimplemented methods in int, float and str. Implementation of additional Math and CMath methods
Design Specification
Following is the implementation of the project:
 All the methods of types Int, Float and Complex are easy to implement
Simple Methods:
•	Int() 
•	__format__() 
•	__dir__()
•	_mul__()
•	__pow__() with modulo
•	__round__() with ndigits 

Complex methods
•	maketrans()
•	translate()
•	isprintable()
•	isnumeric()
•	format()
•	format_map()
•	encode()
•	casefold()
•	__rmod__()

  
= EXPERIENCE = 
  
**1) What programming languages are you fluent in?** 
Which tools do you normally use for development? 
I am fluent in Python, Java, Android, C++, C. Otherwise I can also program in PHP, Javascript, CSS. 
 
I use both Linux(Ubuntu 16.04) and Windows on my laptop. For development I prefer Linux unless the language is Microsoft specific(eg. C#). I am quite familiar with the terminal and hardly use my mouse. I prefer to use the combination of an editor and the terminal rather than an IDE for development. I use Codeblocks and Atom for editing purposes
  
**2) What is my experience with Open Source?**
I am pursuing B-Tech Computer Science with specialization in Open Source and Open Standards at University of Petroleum and Energy Studies, Dehradun, India. Open Source is my domain and I have special skills and knowledge regarding the same. I find Open Source and Open Standards very liberal and secure art the same time. It allows us to adjust our needs and availability accordingly as per the demand of the project. 
 

**3)What is my experience with Python and Java Programming?**
I have been doing progamming in Python since the first year and Java since the second year.
I am fully versed with Python and Java programming and able to do projects. Currently I am doing a project in my college for Minor 2 that encorporates both the technologies.
I have also certified for Python Programming by IIT Bombay by Remote and for Java by Oracle.

**Timeline:**  
  
**May 05 to May 30**
Discuss the project with my mentor in further detail and get familiar with the Beeware. Explore their repository and the pseudo-codes that requires implementation and study them in depth. 
Begin with the documentation alongside

**May 30 to June 12**
Research and analyse encode(), format() and format_map() functions, Unicode.
Implementation of string functions: isidentifier(), maketrans()
Implementation of float functions: pow(), round()
Documentation

**June 13 to June 20**
Implementation of  hashmap to emulate a dictionary in Java.
Implementation of string functions: replace(), isnumeric(), isprintable()
Continue research of encode() and Unicode
Continue documentation

**June 21 to June 29**
Implement format() and format_map()
Implementation of string functions: casefold() and splitlines(), rmul()
Implementation of complex functions: __bool__(), __dir__(), __float__()
Documentation refinement.

**June 30 - July 7**
Finish research on encode() format_map() and format().
Test all the functions implemented
Finalize documentation for Phase 1 evaluation

**July 7 - July 16**
Implementation of String function: rpartition()
Implement and test encode()
Test implementation of isprintable() and isnumeric()
Begin Phase-2 Documentation

**July 17 - July 29** 	
Implement r methods for Int 
Implement r methods for Float
Implement r methods for complex
Finalize Documentation for Phase 2

**July 30 - August 7** 	 
Finish implementation of remaining functions()
Implement and test float functions: _dir_() and format(), _pow_()
Implementation of string functions: _dir_() 
Finish implementation of r methods for int, float and complex

**August 8 - 16** 	
Test all the implementation
Refine and recheck implementations for errors. 
Finalize the final document
Mentor review of final project

**August 17 - 29** 	
Polishing of the final product with the consultancy of the mentor.
Rechecking by mentor for assured success of project.
**Final submission.**
    
 
 
**Why I should be selected for GSOC?** 
 
I’m an enthusiastic developer. I have rich experience working on team projects. Also I’ve known the importance of the various phases of software engineering. I am an Open Source student and so, the project lies entirely in my domain. The in depth knowledge of Open Source and its tools will help me in processing the modules of the project. I have good knowledge of Java and Python and have obtained Certification in both programming languages by reputed Institutions.  While developing anything I do stress upon the design phase and testing phase. I can easily go through a particular documentation and use it’s API as per my need. 
I document code while writing it. It really helps the future development process. I am known to meet hard deadlines. I don’t give up easily and promise to adhere strictly to the deadlines mentioned in the above table. I know my capabilities perfectly and have formulated the timeline accordingly. I know when to ask for help and when not to. 
The main reason behind my application is my zeal to imbibe from the project and help in the development of a project that benefits all.  This project will also be a very good learning curve for me. It will be my first contribution to such a big organization. I would communicate with my mentor every week and will discuss with him my progress, objectives or any issue that I am facing. Apart from this, this project shall help me nurture my programming skills and add a dimension to my horizon. Something that urged me to pick this project is my vision on decreasing complexity and increasing efficiency.

**Comment by freakboy3742** [comment]
Unfortunately, this proposal wasn't accepted.
