### ISSUE TITLE
Support for chained comparisons

### ISSUE THREAD

**Issue by eliasdorneles** [pybee/voc#540]
[Chained comparisons](https://docs.python.org/3/reference/expressions.html#comparisons) are used in many standard library modules, including the [urllib.request.parse](https://github.com/pybee/ouroboros/blob/master/ouroboros/urllib/parse.py#L158) which is good to prioritize.

The following test code:

```
print(1 == 1 == 1)
print(1 == 1 == 2)
print(1 == 1 != 2)
print(1 == 1 < 2)
print(3 == 3 < 2)
print(1 < 2 < 3 > 2)
```

When running with CPython, it prints:

```
$ python multiplecomparators.py
True
False
True
True
False
True
```

With VOC, the compilation fails because [the syntax isn't supported yet](https://github.com/pybee/voc/blob/master/voc/python/ast.py#L1743):

    NotImplementedError: Don't know how to resolve multiple comparators

Fixing this will need updating the `visit_Compare` method in `voc/python/ast.py` to generate the proper bytecode for chained comparisons.

**Comment by katlings** [comment]
I'm interested in tackling this!
