### ISSUE TITLE
Support deleting variables from local namespace

### ISSUE THREAD

**Issue by eliasdorneles** [pybee/voc#565]
The following piece of code fails to compile with VOC:

```
a = 1
print('a' in locals())

del a
print('a' in locals())
```

Attempting to compile this, we get an error because it lacks implementation:

    NotImplementedError: Unknown context <_ast.Del object at 0x7f24c407c7b8>

This is used in several modules in the standard library (mostly to prevent cluttering the namespace), including `urllib.parse`. Therefore, fixing this will help us o get closer to making HTTP requests. :)

**Comment by katlings** [comment]
I'm working on this!
