### ISSUE TITLE
str.repr should use double quotes when value needs escaping

### ISSUE THREAD

**Issue by eliasdorneles** [pybee/voc#568]
This is what CPython does:

```
>>> s = "hello"
>>> repr(s)
"'hello'"
>>> s = "hello'"
>>> repr(s)
'"hello\'"'
```

Code compiled with VOC is currently working like this:

```
>>> s = "hello"
>>> repr(s)  # this works as expected ...
'hello'
>>> s = "hello'"
>>> repr(s)  # ... but this results in broken representation
'hello''
```

It would be nice to have [`Str.__repr__`](https://github.com/pybee/voc/blob/7771f960087589755674e8c608c1540dbb85251f/python/common/org/python/types/Str.java#L72-L74) handling these cases, this will make testing easier.

**Comment by cflee** [comment]
If anyone is tackling this, `Bytes.__repr__` also needs similar logic.

For reference: [cpython bytesobject.c](https://github.com/python/cpython/blob/v3.6.1/Objects/bytesobject.c#L1320)

**Comment by cflee** [comment]
Actually, should this issue be generalised to include escaping within the quotes, or should it be a separate issue? There is a partial fix that handles edge cases for representing/escaping various non-printable characters (but not the outer quotes) in newly-closed #465, and I'm wondering where to track that.

CPython ref: [unicodeobject.c](https://github.com/python/cpython/blob/v3.5.3/Objects/unicodeobject.c#L12407)

**Comment by seocam** [comment]
Well the first issue (created by @eliasdorneles) would be fixed by #578 but still there things to be done to get this closer to the CPython ref.

**Comment by starlord1311** [comment]
@eliasdorneles can i take up this issue?

**Comment by jonkiparsky** [comment]
This seems to be up for grabs, so I'm going to see what I can do with it. If I don't make traction, I will come back and restore the "Up for grabs" tag.

**Comment by eliasdorneles** [comment]
@jonkiparsky feel free to have a look around!
However, I was just checking and the specific case I reported seems that it was already implemented... Did you find anything?

**Comment by jonkiparsky** [comment]
@eliasdorneles

Yep, looks good from here. 

```
(env) [jpk@Jons-MacBook-Pro-2/~/code/voc-dev/jpk_test: Sun May 20 15:45]:547 $ java -classpath ../voc/dist/python-java-support.jar:. python.quote_test
'hello'
hello'
'hello
"'hello"'
(env) [jpk@Jons-MacBook-Pro-2/~/code/voc-dev/jpk_test: Sun May 20 15:45]:548 $ python3 quote_test.py 
'hello'
hello'
'hello
"'hello"'
(env) [jpk@Jons-MacBook-Pro-2/~/code/voc-dev/jpk_test: Sun May 20 15:45]:549 $ cat quote_test.py 
class quote_test(object):
    s = "'hello'"
    t = "hello'"
    u = "'hello"
    v = '"\'hello"\''
    print(s)
    print(t)
    print(u)
    print(v)
(env) [jpk@Jons-MacBook-Pro-2/~/code/voc-dev/jpk_test: Sun May 20 15:46]:550 $ 
```

I suppose this issue can be closed?

**Comment by eliasdorneles** [comment]
Yup, seems like it!
Closing it now, thanks for digging! :+1:
