### ISSUE TITLE
Missing support for inner classes

### ISSUE THREAD

**Issue by trbedwards** [pybee/voc#586]
I cannot compile a python script with inner classes. For example, in my `voc_test.py` file:

```
class Thing(object):
    class InnerThing(object):
        pass
```

I invoke `voc voc_test.py` and get this error:

```
Traceback (most recent call last):
  File "/Users/tre11/anaconda2/envs/python3.5/lib/python3.5/site-packages/voc/python/ast.py", line 160, in visit
    super().visit(node)
  File "/Users/tre11/anaconda2/envs/python3.5/lib/python3.5/ast.py", line 245, in visit
    return visitor(node)
  File "/Users/tre11/anaconda2/envs/python3.5/lib/python3.5/site-packages/voc/python/ast.py", line 49, in dec
    fn(self, node, *args, **kwargs)
  File "/Users/tre11/anaconda2/envs/python3.5/lib/python3.5/site-packages/voc/python/ast.py", line 284, in visit_ClassDef
    klass = self.context.add_class(class_name, extends, implements)
AttributeError: 'Class' object has no attribute 'add_class'

Problem occurred in voc_test.py
Node: ClassDef(name='InnerThing', bases=[
    Name(id='object', ctx=Load(), lineno=2, col_offset=21),
  ], keywords=[], body=[
    Pass(lineno=3, col_offset=8),
  ], decorator_list=[], lineno=2, col_offset=4)
```

I am using python 3.5 and the latest master version of voc

**Comment by trbedwards** [comment]
For context, I'm trying to compile [`dateutil.parser`](https://dateutil.readthedocs.io/en/stable/parser.html)

**Comment by eliasdorneles** [comment]
Thanks for reporting!
The solution to this is to add an `add_class` method to [`Class` class in the klass.py file](https://github.com/pybee/voc/blob/e7479dc3dbd0051a69ed3876fbdc9d20683bd553/voc/python/klass.py#L19) similar [to the one in module.py](https://github.com/pybee/voc/blob/e7479dc3dbd0051a69ed3876fbdc9d20683bd553/voc/python/modules.py#L177-L232).
Which is also quite similar to the one in [methods.py](https://github.com/pybee/voc/blob/master/voc/python/methods.py#L372-L427), it might be interesting to refactor the common parts.
