### ISSUE TITLE
Use a hidden name for python functions

### ISSUE THREAD

**Issue by freakboy3742** [pybee/voc#59]
If you define a method in Python, VOC will potentially generate three Java-side methods to represent that method:
- A _binding_ method, representing the Java interface to the method. This will be typed using the specific types annotated in the Python code
- A _super_ method, with the same prototype as the binding, but explicitly invoking the super.method()
- The _Implementation_, representing the actual Python logic. All arguments to this method will be `org.python.Object`, as will the return type. All implementation methods are static; the first argument is the `org.python.Object` representing the instance. This largely mirrors Python's own behavior.

When you invoke a Python method from within Python, the implementation is called directly. However, if you invoke from Java, the _binding_ is invoked; this transforms the typed arguments into Python-compatible objects, and invokes the implementation.

At present, the implementation and binding have the same method name, but different prototypes (pure Java types for the binding; static `org.python.Object` types for the implementation). However, if a method `foobar()` needs a super, the super method will be called `foobar$super()`. This is _not_ a legal name in Java syntax, but it is a legal and accessible _symbol_ name. As a result, we can create a super method without any risk of namespace clashes. 

It would be desirable for the implementation method to also have a modifier (`foobar$py()`) to make it clear that the method should only be invoked from within a Python context.

**Comment by leasunhy** [comment]
Hi, I'm currently attempting on this.
After I added the `$py` suffix to the methods (not functions), all instance methods including the built-ins are affected.

Then I ran `voc` on the following python code:

```python
class h:
    def __init__(self):
        pass

h()
```
and it yielded:

```text
Exception in thread "main" java.lang.NoSuchMethodException: python.q.h.__init__(org.python.Object)
        at java.lang.Class.getMethod(Class.java:1786)
        at python.q.h.class$init(q.py:2)
        at python.q.__init__.module$import(q.py:1)
        at python.q.__init__.main(q.py)
```

By disassembling the generated class file, I confirmed that the method that was being looked for was renamed to `__init__$py`.

After searching in the code for more than an hour, the code which causes the exception is still not found.

Anyone who knows the internals of `voc`? 🤕 Any help is appreciated!

**Comment by leasunhy** [comment]
Hi, I'm currently attempting on #53.
After I added the `$py` suffix to the methods (not functions), all instance methods including the built-ins are affected.

Then I ran `voc` on the following python code:

```python
class h:
    def __init__(self):
        pass

h()
```
and it yielded:

```text
Exception in thread "main" java.lang.NoSuchMethodException: python.q.h.__init__(org.python.Object)
        at java.lang.Class.getMethod(Class.java:1786)
        at python.q.h.class$init(q.py:2)
        at python.q.__init__.module$import(q.py:1)
        at python.q.__init__.main(q.py)
```

By disassembling the generated class file, I confirmed that the method that was being looked for was renamed to `__init__$py`.

After searching in the code for more than an hour, the code which causes the exception is still not found.

Anyone who knows the internals of `voc`? 🤕 Any help is appreciated!

**Comment by leasunhy** [comment]
OK I have fixed it!
