### ISSUE TITLE
Support for if conditions in list comprehensions

### ISSUE THREAD

**Issue by onyb** [pybee/voc#683]
Currently VOC supports `list` (and also `set`, `dict`, `generator`) comprehensions, but ignores any `if` conditions present.

**Excepted result:**
```py
>>> [i for i in range(10) if i % 2 == 0]
[0, 2, 4, 6, 8]
```

**Current result in VOC:**
```py
>>> [i for i in range(10) if i % 2 == 0]
[0, 1, 2, 3, 4, 5, 6, 7, 8, 9]
```

I am interested in working on a fix, but would need some pointers.

**Comment by eliasdorneles** [comment]
Thanks for reporting @onyb, indeed list comprehensions are missing some features !

Support for list comprehensions is implemented in [the `visit_ListComp` method](https://github.com/pybee/voc/blob/efc121a2a112b458a66b3ce39bccb55a78197856/voc/python/ast.py#L1175) of the ast visitor class.

From a quick glance, I believe [these lines](https://github.com/pybee/voc/blob/efc121a2a112b458a66b3ce39bccb55a78197856/voc/python/ast.py#L1246-L1254) have to be evaluated only if the condition is truthy.
