### ISSUE TITLE
Could not find or load main class

### ISSUE THREAD

**Issue by MisterY** [pybee/voc#747]
This might be a silly question but I'm getting "Error: Could not find or load main class python.hello" no matter what I try.
Following the [Tutorial](https://voc.readthedocs.io/en/latest/tutorial/tutorial-0.html), I've installed VOC, using OpenJDK that comes with Android Studio
```
(env) λ javac -version
javac 1.8.0_152-release
```
VOC is installed as per instructions, directly from GitHub. Virtualenv has been created and VOC installed via `pip -e`. Ant generated python-java-support.jar.

Then I've created a separate directory for the small test project. Created `hello.py` with only the print command. VOC compiled it into python\hello.class.

javap confirms the class was created:
```
(env) λ javap .\hello.class
Compiled from "hello.py"
public class python.hello extends org.python.types.Module {
  public void module$import();
  public python.hello();
  public org.python.Object __new__(org.python.Object);
  public static void main(java.lang.String[]);
}
```

However, whether I call from the directory where hello.py is, or from python directory, I'm getting the above error. I moved the .jar file into python directory and am running
```
(env) λ java -classpath python-java-support.jar:. python.hello
```
to no avail. Any hints, please? Thanks!

**Comment by MisterY** [comment]
OK, last minute detail-check identifies the cause of the error:

- On Linux/OSX:
```
$ java -classpath ../voc/dist/python-java-support.jar:. python.example
Hello World!
```
- On Windows:
```
> java -classpath ../voc/dist/python-java-support.jar;. python.example
Hello World!
```

I've typed the first command, using ":" instead of ";". :-S

**Comment by MisterY** [comment]
That resolved my original problem but now a vendor is missing:
```
(env) λ java -classpath python-java-support.jar;. python.hello
Exception in thread "main" java.lang.ExceptionInInitializerError
        at python.sys.<clinit>(sys.java:76)
        at python.hello.main(hello.py)
Caused by: RuntimeError: Unknown platform vendor 'JetBrains s.r.o'
        at python.platform.<clinit>(platform.java:31)
        ... 2 more
```
just like #722.

**Comment by MisterY** [comment]
After the fix: Yay!
```
(env) λ java -classpath python-java-support.jar;. python.hello
Hello world!
```

**Comment by eliasdorneles** [comment]
Right, that `:` in Linux/Mac vs `;` in Windows is annoying!

About the vendor thing, since it seems there will be lots of these, maybe we should replace the code in https://github.com/pybee/voc/blob/e2fc0d2c542a7bb7a3b9ff636718d301d520affc/python/common/python/platform.java#L24-L32 for this:

```
if (vendor.equals("The Android Project")) {
    platform_class_name = "python._platform.AndroidPlatform";
} else {
    platform_class_name = "python._platform.JavaPlatform";
}
```

Do you want to send a PR for that? :)

**Comment by MisterY** [comment]
Yup. Just did. 
Now off to trying out something more substantial. :D
I need to port a few libraries to Android.

**Comment by eliasdorneles** [comment]
Awesome! :)
I've just added a comment there.

**Comment by MisterY** [comment]
Great idea! I've rewritten that if tree as suggested.
