### ISSUE TITLE
`==` with bytearray and str behaves like python2, calls Str.encode() implicitly Refs#36

### ISSUE THREAD

**Issue by sziraqui** [pybee/voc#752]
While trying to implement `bytearray==str` in `ByteArray.__eq__` method I found python2 like behaviour.
This is the code I wrote:
```
if __name__=="__main__":
	a = bytearray('abcd','utf-8')
	s = str('abcd')
	l = ['a','b','c','d']
	print("a==s ", a==s)
	print("a==l ", a==l)
```
This gave the following error
```
Exception in thread "main" NotImplementedError: encode() has not been implemented.
	at org.python.types.Str.encode(Str.java:650)
	at org.python.types.ByteArray.<init>(ByteArray.java:67)
	...
```
CPython3 will not call str.encode() implicitly.

Related reading-

[Python docs](https://docs.python.org/3.0/whatsnew/3.0.html#text-vs-data-instead-of-unicode-vs-8-bit)

[SO post](https://stackoverflow.com/a/30580865/6699069)
#36

**Comment by sziraqui** [comment]
#36

**Comment by eliasdorneles** [comment]
Actually, `bytearray('abcd','utf-8')` is the equivalent to `bytearray('abcd'.encode('utf-8'))`.

See: https://docs.python.org/3/library/functions.html#func-bytearray

> If it is a string, you must also give the encoding (and optionally, errors) parameters; bytearray() then converts the string to bytes using str.encode().
