### ISSUE TITLE
docker image

### ISSUE THREAD

**Issue by jedie** [pybee/voc#766]
Is there a docker image that contains a working VOC environment for development as described here: https://voc.readthedocs.io/en/latest/background/install.html ?!?

**Comment by cflee** [comment]
I don't think so, but that would make an interesting contribution, if there aren't any existing images that already have the JDK, Python and Ant installed!

**Comment by jedie** [comment]
Hm... OK, i will try it ;)

**Comment by cflee** [comment]
For future visitors to this issue, please see discussion in #767 – @jedie is now continuing this at https://github.com/jedie/pybee-docker. Thanks!
