### ISSUE TITLE
[GSoC] Completing the Implementation of Builtin Data Types Bool, Tuple, Set, and String

### ISSUE THREAD

**Issue by heyjessi** [pybee/voc#774]
# Summary of Goals

This summer, I hope to support the implementation for several builtin data types which I'll be able to work on until the VOC version conforms to the CPython Library. This includes, but is not limited to
- Booleans
- Tuples
- Sets
- Strings

# Project Description

I am interested in working with VOC: Python on the JVM Project. Specifically, I want to engage in a couple of the previously proposed projects. After taking several days to read through the VOC documentation and set up my developer’s environment, I became very intrigued with the conception of transpilers for bytecode, especially since it makes Java bytecode from Python bytecode, which is an easy to use language for beginners (especially one to teach to students not yet in college) and similarly a powerful language for developers. I am personally interested in completing the implementation of primitive types bool, tuple, set, and string and if time allows, other types that don’t have their full implementations.

Currently, VOC has a functional implementation for bool, tuple, set, and string but doesn’t have full implementation of these types. The following methods need to be implemented: 

- String is missing the implementations for ```zfill```, ```rindex```, ```rjust```, etc 
- Tuple is missing implementations for ```round```
- Set is missing implementations for ```rsub```, ```rand```, ```rxor```, etc
- Bool is missing implementations for ```radd```, ```rmod```, ```rdivmod```, ```rpow```, etc

In order to effectively execute this project, I’ll be able to reference the CPython Library (and may reuse code if necessary) in order to implement these methods. Here are some of the specific ways I'll be able to achieve these goals.

### Reverse Methods
Methods that keep popping up in most of the builtin data types that I'm considering implementing are **reverse methods** such as ```radd``` and ```rmod```. Currently, VOC doesn't support these reverse methods, which is important since it allows the sum/add function to default to reverse add when the operands have different types and the left operand doesn't support the right operand in the algebra _(0 + type Banana v. reverse add with type Banana + 0)_. 

There are several ways that I may try to implement these methods fairly quickly: I can recognize that the method and the reverse method are commutative and implement the reverse method using the non-reverse method. This is exemplified in the ```radd``` Banana example above. However, if this isn't the case (string concatenation for example), I will define the normal and reversed methods separately. It's important to note that the leftmost object in the ```radd``` example above must not return ```NotImplemented``` for its non reversed method. This ensures that ```radd``` is only called when the function ```add``` fails.

### InPlace Operators
Implementing the in-place operators (transforms the input) are fairly straightforward in the set implementation. In-place operators provide quick access to primitive functions such as addition, subtraction, multiplication, and division with respectively +=, -= (the same thing as ```isub```), *=, /=, etc. In the case of the set methods implemented in VOC, the methods needed are ```isub```, ```ixor``` (a ^= b), ```iand``` (a &= b), ```ior``` (a |= b). The latter two methods refer to intersection and union operations. These methods can be successfully implemented by recognizing that the inplace methods take in two arguments and change the first argument to an accumulator/sum.

### Format and Format_Map
I will be implementing ```format``` methods for String and Bool types. Essentially, ```format``` offers the developer a way to insert a string or bool into a replacement field, which is surrounded by curly braces { }. While some cases will require the developer to specify the replacement field, other cases such as sequence or index have default numerical values and do not require replacement fields. Implementing format would require me to understand the new format syntax which includes accessing arguments by position and name, expressing percentages and commas in large numbers, type-specific format (date and time), nesting arguments, and many more examples that I have looked into. Since format contains a wealth of operations, I will be able to break down my implementation into feasible steps.

### Encode
In order to understand encode for strings, I will need to dive deep into Unicode (base 16) and byte processing. This requires me to understand that there are several ways to implement encode depending on the UTF used (such as UTF-8). I will also have to understand codecs, a module that defines base classes for encoders and decoders and gives access to various encodings. I will also have to understand the errors parameter of encode and the arguments ```strict```, ```ignore```, ```replace```, ```xmlcharrefreplace```, and a few others which affect how ```encode``` is executed.

### Translate
Translate methods complete the process of returning the value of a string translated via a table. When implementing translate, I will need to know more about the function ```maketrans``` (which I'll be implementing the week before). ```maketrans``` gives a mapping of integers and chars to integers, strings, or None. The functionality also varies with the number of arguments. If it's only one argument, then it must be a dictionary that already contains a mapping. If two arguments are passed into ```maketrans``` I will need to check if they are of the same length, or else the mapping will not be accurate and an exception must be raised. With three arguments, the third argument's characters will map to Nothing. Keeping in mind these cases, I will be able to successfully implement ```maketrans```. While ```maketrans``` method outputs a type of table, ```translate``` outputs a string value. One of the arguments in the ```translate``` method allows for the developer to delete specific characters from a specific list.

Ultimately, the goal of the summer would be to have types tuple, string, and bool completely match Python’s versions of tuple, string, set and bool.

# Project Plan

**Until May 14** - In order to implement the changes that I want to make, I will need to have a working understanding of the BeeWare Codebase and VOC. I’ve already checked out a couple of tutorials for VOC, but in the meantime, I’ll be able to make small contributions to the BeeWare Codebase by referencing the first time VOC contribution documentation and tickets. I will stay active in the BeeWare community on Gitter, ask questions, and read more of the documentation about VOC and bytecode transpilers. Once I know my assignment, I can begin working out and understanding how I will implement these changes over the summer.

## Phase 1 
_**May 14-June 15 Complete the implementation of Bool in Bool.java and complete the implementation of Tuple in Tuple.java**_

- May 14 - May 21 Read more about the current Bool.java Library and Implement ```rtruediv```, ```rfloordiv```, ```rmod```,```radd```, ```rmul```, ```rdivmod```, ```rpow```, ```rlshift```, ```rrshift```, ```rand```, ```rxor```, ```ror```, and finish any other reverse methods
- May 21 - May 28 Start implementing ```format```
- May 28 - June 8 Finish Implementing ```format``` and finish typing up the doc for all methods in the Bool.java file that haven’t been written clearly.
- June 8 - June 15 Read more about the current Tuple.java library and Implement ```round``` and any other methods

## Phase 2 
_**June 15-July 13  Set in Set.java and begin the implementation of String in String.java**_

- June 15 - 23 Read more about the current Set.java library and implement ```rsub```, ```rand```, ```rxor```, ```ror``` and finish any other reverse methods
- June 23 - 30 Implement ```isub```, ```iand```, ```ixor```, ```ior``` and finish any other inplace operations, read more about the current String.java library and implement ```rmul```, ```rmod```, ```zfill```
- June 30 - July 6 Implement ```format```
- July 6 - July 13 Implement ```format_map```

## Phase 3 
_**July 13-Aug 20 Complete the implementation of String in String.java**_

- July 13 - July 20  Implement ```encode```
- July 20 - July 27 Implement ```maketrans```
- July 27 - Aug 7  Implement ```translate```
- Aug 7- Aug 14 Implement ```transplit```
- Aug 14 - Aug 21 Finish and polish implementations methods from the summer and implement other methods in other builtin types if time allows

# Risk Analysis

As a first-year computer science student and first-time open source contributor, there are many gaps in my knowledge about technical terms like bytecode transpilers, VOC documentation (testing), reading bytecode, etc. I made sure that I chose VOC during my research of GSoC BeeWare, an open source project that I know will be able to contribute to through my knowledge of Java and Python, research, and feasible goals. After reading through much of the documentation and the First Time Contributors Guide, I found that the BeeWare community is very open and accessible to First Time Contributors like myself who want to rigorously immerse themselves in an open source community.

As stated in the initial project guide, finishing the implementation of one builtin data type such as Bool would be enough for some in the summer; therefore, I know that tackling the implementations of several different types such as ```format``` and ```encode```  will be an ambitious challenge. However, some methods (such as reverse methods) may not take as much time as I initially think so I may end up spending more time on methods such as ```format``` and ```encode```. Therefore, my project timeline may shift up and I'll have to make more feasible goals for the summer, which could include looking at other data types and finishing implementations.

I will make sure to keep track of my progress for GSoC by asking tough questions about my various implementations to my mentor after researching the topic(s) extensively on my own, explaining my conceptual thought process out loud so that my mentor can help me where I am going wrong, and contributing directly to BeeWare's open source community through Gitter and other online platforms. I sincerely hope that I can learn a great deal this summer through my own research and with the help of a mentor and contribute to BeeWare’s codebase to the best of my knowledge as a first-time contributor. I hope to be able to sustain this connection and become an active contributor to the BeeWare open source community and serve as a teacher and mentor to other students interested in doing so.

**Comment by freakboy3742** [comment]
This is a really solid first draft - nice work!

The end goal of "fully compliant string, bool, tuple and set" definitely strikes me as something that is achievable; however, I think you may need to do a little more digging into how much effort is involved in some of the missing methods.

You've given great detail of the "r" methods; however, have you dug into exactly what needs to be done to implement them? In many cases, you'll find the answer is really simple - to the tune that you may be able to implement several of those methods *a day*, not need a week to implement 3 or 4. 

In some cases, you may even be able to fall back on a common implementation. 

There will be some for which this isn't true, but it probably warrants a little more investigation.

On the other hand, some of the methods you've proposed (I'm looking at `encode` and `format` in particular) hide a multitude of dragons :-) You might want to take a closer look at what is involved for those.

**Comment by heyjessi** [comment]
Hi @freakboy3742! 

Thank you so much for the feedback. I've had a chance to research the functions I'm interested in implementing over the past couple of days including ```encode``` and ```format```. I realize that these will take longer and require me to have a solid understanding of their frameworks and the applications of the methods as well as their exception cases. I've updated my project description with several paragraphs about specific methods to reflect this research and my goals for implementing these successfully.

I've also modified my project plan timeline to reflect the difficulties of implementing certain methods over others. Once I learn how to implement the "r" methods, then it's implementation should be relatively straightforward for other builtin data types and give me more time to research and test the harder functions. Please let me know if I should further modify my project plan to give me the best chance of succeeding in this project long term.

And also please let me know if I'm misinterpreting any information in this doc or if my project proposal is still missing any relevant information that you'd like to see in the final PDF proposal. Thank you again and have a great weekend!

**Comment by freakboy3742** [comment]
@heyjessi This looks a lot better. There are still a couple of minor problems (for example, "dir" isn't a type-specific method you'll have to implement - it's a part of the core data model); but otherwise, this is probably ready for final submission.

**Comment by freakboy3742** [comment]
Unfortunately, this project was not selected for the 2018 GSoC. Thanks for applying!
