### ISSUE TITLE
Links to other documents not working

### ISSUE THREAD

**Issue by ankush981** [pybee/voc#81]
If we look at the Getting Started document, towards the end we have what looks like a broken link:  :doc:`start the first tutorial </tutorials/tutorial-0>`. I tried to modify it to GitHub relative link format as given [here](https://help.github.com/articles/relative-links-in-readmes/) but couldn't get it right. How are these to be fixed?

**Comment by ankush981** [comment]
Ah, I realize this might be the 'Read the Docs' format. Does that mean we leave it like this here?

**Comment by freakboy3742** [comment]
It's Sphinx format, not something specific to Read the Docs, but yes. Sphinx is a set of extensions to ReStructuredText that provides rich indexing, and output to formats other than HTML. Unfortunately, Github supports ReST, but not Sphinx, so the doc pages look a little crusty if you view them in GitHub - but luckily, RTD exists if you want to browse documentation.
