### ISSUE TITLE
Floating Point Representations

### ISSUE THREAD

**Issue by AnimeshSinha1309** [pybee/voc#936]
When performing floating point number division, `10.0 / 3`, the Python compiler gives 3.3333333333333333 as the result, where as Vox gives 3.3333333333333335, and so does Java. I think that using `float this.value` to represent decimals is the issue, cause Python and Java represent decimals differently.

**Comment by freakboy3742** [comment]
@AnimeshSinha1309 That should be addressed by the VOC test suite. The test suite does a series of output normalisations (including floating point format normalization) as part of the execution process; if that isn't working, then either the test you're running isn't applying those normalisations correctly, or you've found an edge case where the normalisations aren't working. 

I can't think of an obvious reason why `10.0/3` would trigger any problems; the cleansing process should ensure only 5 decimal places of precision are compared (see [this code](https://github.com/pybee/voc/blob/master/tests/utils.py#L222) for where that is set up).

**Comment by AnimeshSinha1309** [comment]
My apologies. It seems like it's a Python versions issue. And now Python also does the same thing. Python 3.6 that is.
