### ISSUE TITLE
'voc' is not recognized as an internal or external command

### ISSUE THREAD

**Issue by geekaara** [pybee/voc#939]
After I created the environment when I try to run example.py it showed this error.

**Comment by freakboy3742** [comment]
It's almost impossible to help diagnose a problem like this without context. We need to know what you've done, and what error messages (if any) you saw, and what platform you're working on (Windows/Mac, etc)

If `voc` isn't appearing as a command, then you've done *something* wrong in the installation process - the install either hasn't completed correctly, or you haven't activated your virtual environment correctly.
